window.FabioV3=window.FabioV3||{};
(()=>{
const FOCUS_KEY='fabioV3FocusNode',FILTER_KEY='fabioV3NodeFilter';
const state={nodeId:null,filter:'all',pool:[],loading:false,compareResources:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route=()=>{const p=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);return{page:p[0]||'dashboard',id:p[1]?decodeURIComponent(p[1]):null}};
const rand=a=>a[Math.floor(Math.random()*a.length)];
function setFocusNode(id){if(!id)return;state.nodeId=id;try{sessionStorage.setItem(FOCUS_KEY,id)}catch{}}
function savedNode(){try{return sessionStorage.getItem(FOCUS_KEY)}catch{return null}}
function setFilter(v){state.filter=v||'all';try{sessionStorage.setItem(FILTER_KEY,state.filter)}catch{}}
function savedFilter(){try{return sessionStorage.getItem(FILTER_KEY)||'all'}catch{return'all'}}
function currentCase(){const id=route().id;return FabioV2.store?.state?.cases?.find(c=>c.id===id)||null}
function nodeTitle(id){const n=FabioV2.nodeMap?.[id];return n?`${n.code} ${n.short||n.title}`:id}
async function loadPool(){if(!state.nodeId||state.loading)return state.pool;state.loading=true;try{const answer=state.filter==='yes'?true:state.filter==='no'?false:null;state.pool=await FabioV2.store.loadNodeCases(state.nodeId,{limit:2500,answer});return state.pool}finally{state.loading=false}}
function indexOfCurrent(){const id=route().id;return Math.max(0,state.pool.findIndex(c=>c.id===id))}
function goCase(c){if(!c)return;setFocusNode(state.nodeId);location.hash='#/replay/'+encodeURIComponent(c.id)}
async function navigate(step){await loadPool();if(!state.pool.length)return;let i=indexOfCurrent();if(step==='random')return goCase(rand(state.pool));i=(i+(Number(step)||0)+state.pool.length)%state.pool.length;goCase(state.pool[i])}
function updateBar(){const bar=$('#nodeDrillbar');if(!bar)return;const i=state.pool.findIndex(c=>c.id===route().id);const count=bar.querySelector('.counter');if(count)count.textContent=state.pool.length?(i>=0?`${i+1} / ${state.pool.length}`:`— / ${state.pool.length}`):'0 cases';bar.querySelectorAll('[data-nfilter]').forEach(b=>b.classList.toggle('active',b.dataset.nfilter===state.filter));}
async function rebuildBar(){const toolbar=$('.replay-toolbar');if(!toolbar)return;state.nodeId=savedNode()||FabioV3.visualUI?.selectedNode||$('.visual-node-row.focused')?.dataset.nodeId||state.nodeId;if(!state.nodeId){$('#nodeDrillbar')?.remove();return}state.filter=savedFilter();let bar=$('#nodeDrillbar');if(!bar){bar=document.createElement('div');bar.id='nodeDrillbar';bar.className='node-drillbar';toolbar.parentElement.insertBefore(bar,toolbar.nextSibling)}bar.innerHTML=`<div class="drill-label"><b>${esc(nodeTitle(state.nodeId))}</b><span>同節點快速練習</span></div><button data-nav="-1">← 上一個</button><button data-nav="1">下一個 →</button><button data-nav="random">隨機</button><button data-nfilter="all">ALL</button><button data-nfilter="yes">YES</button><button data-nfilter="no">NO</button><span class="counter">載入…</span><button class="compare-yn" data-compare-yn>YES vs NO 對照</button>`;bar.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));bar.querySelectorAll('[data-nfilter]').forEach(b=>b.onclick=async()=>{setFilter(b.dataset.nfilter);state.pool=[];await loadPool();updateBar()});bar.querySelector('[data-compare-yn]').onclick=()=>compareYesNo(state.nodeId);await loadPool();updateBar();autoFocusReplay()}
function autoFocusReplay(){const id=state.nodeId;if(!id)return;let tries=0;const tick=()=>{const layer=FabioV3.pixi?.current?.();if(layer){FabioV3.visualUI?.focusNode?.(id,{scroll:true,mode:'single'});return}if(++tries<30)setTimeout(tick,100)};tick()}
async function renderComparePane(host,c,nodeId){await FabioV2.chart.ensureBars(c);const bars=FabioV2.chart.getBars(c,480000);if(!bars.length){host.innerHTML='<div class="empty-chart">沒有 Replay bars</div>';return null}const chart=klinecharts.init(host,{locale:'zh-TW',timezone:'Asia/Taipei',styles:{grid:{horizontal:{color:'#1b2d41'},vertical:{color:'#142437'}},candle:{bar:{upColor:'#27d3a2',downColor:'#ff6378',upBorderColor:'#27d3a2',downBorderColor:'#ff6378',upWickColor:'#27d3a2',downWickColor:'#ff6378'}}}});chart.setSymbol({ticker:`${c.contract||'MTX'} · ${nodeTitle(nodeId)}`,pricePrecision:0,volumePrecision:0});chart.setPeriod({span:1,type:bars[0]?.firstSeq!=null?'second':'minute'});chart.setDataLoader({getBars:({callback})=>callback(bars,{forward:false,backward:false})});const layer=new FabioV3.pixi.DecisionPixiLayer(host,chart,c,bars,{visualMode:'single'});await new Promise(r=>setTimeout(r,100));await layer.init();layer.setMode('single');const visual=layer.focus(nodeId,{scroll:true});return{chart,layer,host,visual,bars}}
function explainHtml(v){if(!v)return'<div class="v32-explain"><span>定位</span><b>無可用結構</b></div>';const a=v.anchor||{},r=v.range;return`<div class="v32-explain"><span>Decision</span><b>${esc(v.code)} · ${esc(v.label)}</b><span>定位時間</span><b>${a.time?new Date(a.time).toLocaleTimeString('zh-TW',{hour12:false,timeZone:'Asia/Taipei'}):'—'}</b><span>${r?'價格區域':'觸發價位'}</span><b>${r?`${Number(r.low).toLocaleString()} – ${Number(r.high).toLocaleString()}`:(a.price!=null?Number(a.price).toLocaleString():'—')}</b><ul>${(v.reason||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`}
function closeCompare(){for(const r of state.compareResources){try{r.layer?.destroy()}catch{}try{klinecharts.dispose(r.host)}catch{}}state.compareResources=[];$('#v32Compare')?.remove()}
async function showCompare(a,b,nodeId){closeCompare();const modal=document.createElement('div');modal.id='v32Compare';modal.className='v32-compare';modal.innerHTML=`<div class="v32-compare-card"><div class="v32-compare-head"><div><b>YES vs NO · Visual Decision Compare</b><span>${esc(nodeTitle(nodeId))}</span></div><button id="v32Close">✕</button></div><div class="v32-compare-grid"><section class="v32-pane"><div class="v32-pane-head"><div><strong>${esc(a.date||a.trading_date)}</strong><small>${esc(a.id)}</small></div><span class="v32-answer ${a.nodes?.[nodeId]?'yes':'no'}">${a.nodes?.[nodeId]?'YES':'NO'}</span></div><div class="v32-chart" id="v32ChartA"></div><div id="v32ExplainA"></div></section><section class="v32-pane"><div class="v32-pane-head"><div><strong>${esc(b.date||b.trading_date)}</strong><small>${esc(b.id)}</small></div><span class="v32-answer ${b.nodes?.[nodeId]?'yes':'no'}">${b.nodes?.[nodeId]?'YES':'NO'}</span></div><div class="v32-chart" id="v32ChartB"></div><div id="v32ExplainB"></div></section></div></div>`;document.body.appendChild(modal);modal.querySelector('#v32Close').onclick=closeCompare;modal.onclick=e=>{if(e.target===modal)closeCompare()};const ra=await renderComparePane($('#v32ChartA'),a,nodeId),rb=await renderComparePane($('#v32ChartB'),b,nodeId);if(ra)state.compareResources.push(ra);if(rb)state.compareResources.push(rb);$('#v32ExplainA').innerHTML=explainHtml(ra?.visual);$('#v32ExplainB').innerHTML=explainHtml(rb?.visual)}
async function compareYesNo(nodeId){const yes=await FabioV2.store.loadNodeCases(nodeId,{limit:1000,answer:true}),no=await FabioV2.store.loadNodeCases(nodeId,{limit:1000,answer:false});if(!yes.length||!no.length){const host=$('#patternLabCount')||$('#nodeDrillbar .counter');if(host)host.textContent=`需要同時有 YES 與 NO 案例才能對照（YES ${yes.length} / NO ${no.length}）`;return}showCompare(rand(yes),rand(no),nodeId)}
function enhancePatternLab(){const r=route();if(r.page!=='nodes'||!r.id)return;const toolbar=$('#patternLab .pl-toolbar');if(!toolbar||toolbar.querySelector('.pl-v32-actions'))return;const actions=document.createElement('div');actions.className='pl-v32-actions';actions.innerHTML='<button class="yn" data-v32-yn>YES vs NO 視覺對照</button><button data-v32-random>隨機開一筆 Replay</button>';toolbar.appendChild(actions);actions.querySelector('[data-v32-yn]').onclick=()=>compareYesNo(r.id);actions.querySelector('[data-v32-random]').onclick=async()=>{setFocusNode(r.id);setFilter('all');const p=await FabioV2.store.loadNodeCases(r.id,{limit:2500});goCase(rand(p))}}
function syncPractice(){const r=route();if(r.page!=='practice'||!r.id)return;const feedback=$('#practiceFeedback'),answered=Boolean(feedback?.textContent?.trim()),layer=FabioV3.pixi?.current?.();const tools=$('.practice-tools');let chip=tools?.querySelector('.practice-reveal-chip');if(tools&&!chip){chip=document.createElement('span');chip.className='practice-reveal-chip';tools.appendChild(chip)}if(chip){chip.textContent=answered?'已揭露 Decision Visual':'裸圖判斷中';chip.classList.toggle('revealed',answered)}if(layer){if(answered){layer.setMode('single');layer.focus(r.id,{scroll:false})}else{layer.clearFocus();layer.setMode('blind')}}}
function enhance(){const r=route();if(r.page==='replay')rebuildBar();else if($('#nodeDrillbar'))$('#nodeDrillbar').remove();enhancePatternLab();syncPractice()}
document.addEventListener('pointerdown',e=>{const row=e.target.closest?.('.visual-node-row');if(row?.dataset.nodeId){setFocusNode(row.dataset.nodeId);state.pool=[]}const tile=e.target.closest?.('.pl-open');if(tile){const r=route();if(r.page==='nodes'&&r.id){setFocusNode(r.id);setFilter('all');state.pool=[]}}},true);
document.addEventListener('keydown',e=>{if(route().page!=='replay'||!state.nodeId||e.target?.matches?.('input,textarea,select'))return;if(e.key==='['){e.preventDefault();navigate(-1)}if(e.key===']'){e.preventDefault();navigate(1)}if(e.key.toLowerCase()==='g'){e.preventDefault();navigate('random')}});
const mo=new MutationObserver(()=>requestAnimationFrame(enhance));mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true});window.addEventListener('hashchange',()=>setTimeout(enhance,50));setTimeout(enhance,900);
FabioV3.drill={compareYesNo,showCompare,navigate,setFocusNode,setFilter,get state(){return state}};
})();
