window.FabioV3=window.FabioV3||{};
(()=>{
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=v=>v==null?'—':`${Math.round(Number(v)*100)}%`;
const route=()=>location.hash.replace(/^#\/?/,'').split('/').filter(Boolean)[0]||'dashboard';
const nodeName=id=>{const n=FabioV2.nodeMap?.[id];return n?`${n.code} · ${n.short}`:id};
function plan(){const st=FabioV2.store.state;return FabioMasteryCore.buildPlan({nodes:FabioV2.nodes,nodeStats:st.nodeStats,history:st.history,dueReviews:FabioV2.store.dueReviews(),target:st.settings.questionCount||20})}
function scoreClass(x){return x>=85?'good':x>=70?'mid':'weak'}
function balanceText(x){if(!x.total)return'—';return `${x.yes}/${x.no}`}
function sessionRows(p){return p.sessions.map((x,i)=>`<article class="v33-session ${scoreClass(x.score)}"><div class="v33-session-rank">${i+1}</div><div class="v33-session-main"><span>${esc(x.node?.stage||x.node?.branch||'NODE')}</span><b>${esc(nodeName(x.nodeId))}</b><small>Mastery ${x.score}% · Recent ${x.recentAccuracy==null?'—':pct(x.recentAccuracy)} · Streak ${x.streak}</small></div><div class="v33-session-signals"><span>Priority <b>${x.priority}</b></span><span>YES/NO <b>${balanceText(x)}</b></span><span>Due <b>${x.due}</b></span></div><button data-v33-practice="${esc(x.nodeId)}">練這個節點</button></article>`).join('')||'<div class="v33-empty">目前案例不足，先啟動 Scanner 建立可訓練 Node。</div>'}
function masteryRows(p){return p.rows.slice(0,12).map(x=>`<button class="v33-skill ${scoreClass(x.score)}" data-v33-node="${esc(x.nodeId)}"><div><span>${esc(x.node?.code||x.nodeId)}</span><b>${esc(x.node?.short||x.nodeId)}</b><small>${x.trained} 次 · Recent ${x.recentAccuracy==null?'—':pct(x.recentAccuracy)} · Streak ${x.streak}</small></div><strong>${x.score}%</strong><i><u style="width:${x.score}%"></u></i></button>`).join('')}
function wire(host){host?.querySelectorAll('[data-v33-practice]').forEach(b=>b.onclick=()=>{location.hash='#/practice/'+encodeURIComponent(b.dataset.v33Practice)});host?.querySelectorAll('[data-v33-node]').forEach(b=>b.onclick=()=>{location.hash='#/nodes/'+encodeURIComponent(b.dataset.v33Node)});host?.querySelectorAll('[data-v33-replay]').forEach(b=>b.onclick=()=>{location.hash='#/replay/'+encodeURIComponent(b.dataset.v33Replay)});const r=host?.querySelector('[data-v33-review]');if(r)r.onclick=()=>location.hash='#/review'}
function enhanceDashboard(){if(route()!=='dashboard')return;const content=$('#content');if(!content||$('#v33Mastery'))return;const p=plan(),host=document.createElement('section');host.id='v33Mastery';host.className='v33-mastery';host.innerHTML=`<div class="v33-head"><div><span class="v33-kicker">V3.3 · ADAPTIVE MASTERY</span><h2>今天不是亂練：先補最弱的 Decision Node</h2><p>排序同時考慮累積正確率、最近 20 題、練習量、連勝、到期複習與高信心錯題；同分時固定按 Node 排序，結果可重現。</p></div><div class="v33-score"><b>${p.overall}%</b><span>Overall Mastery</span></div></div><div class="v33-today"><div><span>今日進度</span><b>${p.todayAttempts} / ${p.target}</b><i><u style="width:${Math.round(p.todayProgress*100)}%"></u></i></div><div><span>待複習</span><b>${p.dueCount}</b><small>Spaced Repetition</small></div><div><span>錯題佇列</span><b>${p.wrongQueue.length}</b><small>Unique case × node</small></div><div><span>首要弱項</span><b>${esc(p.sessions[0]?.node?.code||'—')}</b><small>${esc(p.sessions[0]?.node?.short||'尚無資料')}</small></div></div><div class="v33-actions"><button class="primary" data-v33-practice="${esc(p.sessions[0]?.nodeId||'MR_CLEAR_RECLAIM')}">▶ 開始今日優先訓練</button><button data-v33-review>↻ 進入錯題 / 到期複習</button></div><div class="v33-grid"><section><div class="v33-title"><h3>今日訓練計畫</h3><span>Priority Queue</span></div>${sessionRows(p)}</section><section><div class="v33-title"><h3>Node Mastery Map</h3><span>Accuracy × Recency × Exposure</span></div><div class="v33-skill-grid">${masteryRows(p)}</div></section></div>`;const anchor=content.querySelector('.stats');if(anchor)anchor.insertAdjacentElement('afterend',host);else content.prepend(host);wire(host)}
function enhanceReview(){if(route()!=='review')return;const content=$('#content');if(!content||$('#v33WeakReview'))return;const p=plan(),host=document.createElement('section');host.id='v33WeakReview';host.className='v33-review';const wrong=p.wrongQueue.slice(0,8);host.innerHTML=`<div class="v33-title"><div><span class="v33-kicker">V3.3 · WEAKNESS REVIEW</span><h3>先修 Mental Model，再追求速度</h3></div><span>${p.dueCount} due · ${p.wrongQueue.length} wrong queue</span></div><div class="v33-review-grid"><div><h4>弱項優先序</h4>${p.sessions.map(x=>`<div class="v33-review-row"><span>${esc(x.node?.code||x.nodeId)}</span><b>${esc(x.node?.short||x.nodeId)}</b><em>${x.score}%</em><button data-v33-practice="${esc(x.nodeId)}">練習</button></div>`).join('')||'<div class="v33-empty">尚未累積足夠訓練資料。</div>'}</div><div><h4>最近唯一錯題</h4>${wrong.map(x=>`<div class="v33-review-row"><span>${esc(FabioV2.nodeMap?.[x.nodeId]?.code||x.nodeId)}</span><b>${esc(x.caseId)}</b><em>C${Number(x.confidence||0)}</em><button data-v33-replay="${esc(x.caseId)}">Replay</button></div>`).join('')||'<div class="v33-empty">目前沒有錯題。</div>'}</div></div>`;content.prepend(host);wire(host)}
function badge(){const logo=$('.logo small');if(logo&&!$('.v33-version')){const b=document.createElement('b');b.className='v33-version';b.textContent=' · V3.3 Mastery';logo.appendChild(b)}}
function enhance(){badge();enhanceDashboard();enhanceReview()}
const mo=new MutationObserver(()=>requestAnimationFrame(enhance));mo.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('hashchange',()=>setTimeout(enhance,40));setTimeout(enhance,900);
FabioV3.mastery={plan,enhance};
})();
