window.FabioV3=window.FabioV3||{};
(()=>{
const R=()=>FabioV3.visualRegistry;
const num=(...v)=>{for(const x of v){const n=Number(x);if(Number.isFinite(n))return n}return null};
const ms=v=>{if(v==null)return null;const n=typeof v==='number'?v:Date.parse(v);return Number.isFinite(n)?n:null};
const secs=(a,b)=>{const x=ms(a),y=ms(b);return x!=null&&y!=null?Math.max(0,(y-x)/1000):null};
const fmt=(n,d=1)=>n==null?'—':Number(n).toFixed(d).replace(/\.0$/,'');
const pct=n=>n==null?'—':`${(Number(n)*100).toFixed(1)}%`;
const truth=(c,id)=>Boolean(c?.nodes?.[id]);
function meta(c,id){return c?.nodeMeta?.[id]||c?.node_meta?.[id]||null}
function nearest(bars,time){const t=ms(time);if(!bars?.length||t==null)return null;let lo=0,hi=bars.length-1;while(lo<hi){const m=(lo+hi)>>1;if(bars[m].timestamp<t)lo=m+1;else hi=m}const a=bars[lo],b=bars[Math.max(0,lo-1)];return !b||Math.abs(a.timestamp-t)<=Math.abs(b.timestamp-t)?a:b}
function decision(c,bars,id,fallbackTime,fallbackPrice){const m=meta(c,id),time=m?.decision_time||m?.time||fallbackTime;const bar=nearest(bars,time);return{time:ms(time??bar?.timestamp),price:num(m?.decision_price,m?.price,fallbackPrice,bar?.close),seq:num(m?.decision_seq,m?.seq,bar?.lastSeq),priceSource:m?.price_source||((m?.decision_price!=null)?'physical_seq':'derived')}}
function boundary(c){const p=c.priorProfile||{},f=c.features||{},side=f.auction_side;return side==='down'?num(p.val,c.val):num(p.vah,c.vah)}
function base(c,id){const cfg=R().spec(id);return{nodeId:id,code:FabioV2.nodeMap?.[id]?.code||id,label:cfg.label,family:cfg.family,layer:cfg.layer,tone:cfg.tone,answer:truth(c,id),metrics:{},reason:[]}}
function finish(v){v.style=R().style(v.nodeId,v.answer);return v}
function resolve(c,bars,id){const v=base(c,id),p=c.priorProfile||{},f=c.features||{},first=bars?.[0]?.timestamp,last=bars?.at(-1)?.timestamp,b=boundary(c),tol=num(f.lvn_tolerance,1)??1,side=f.auction_side;
 if(id==='CTX_VALUE'){const width=num(p.width,c.value_width);v.range={startTime:first,endTime:last,low:num(p.val,c.val),high:num(p.vah,c.vah)};v.lines=[{price:num(p.vah,c.vah),label:'VAH'},{price:num(p.poc,c.poc),label:'POC'},{price:num(p.val,c.val),label:'VAL'}];v.metrics={valueWidth:width};v.reason=[`Previous Value：VAL ${fmt(v.range.low,0)} / POC ${fmt(num(p.poc,c.poc),0)} / VAH ${fmt(v.range.high,0)}`,`Value Width ${fmt(width)} pts`];return finish(v)}
 if(id==='AUC_ATTEMPT'){v.anchor=decision(c,bars,id,c.attemptStartTime||c.attempt_start_time,b);v.reference={price:b,label:side==='down'?'VAL':'VAH'};v.metrics={excursion:num(f.excursion_points),threshold:num(f.excursion_threshold),ratio:num(f.excursion_pct_value)};const delta=v.metrics.excursion!=null&&v.metrics.threshold!=null?v.metrics.excursion-v.metrics.threshold:null;v.reason=[`實際 Excursion ${fmt(v.metrics.excursion)} pts vs 門檻 ${fmt(v.metrics.threshold)} pts`,`距門檻 ${delta==null?'—':`${delta>=0?'+':''}${fmt(delta)} pts`} · ${pct(v.metrics.ratio)} Value Width`];return finish(v)}
 if(id==='AUC_EXTREME'){v.anchor=decision(c,bars,id,c.extremeTime||c.extreme_time,c.extremePrice||c.extreme_price);v.reference={price:b,label:'Value boundary'};v.metrics={extreme:v.anchor.price,excursion:num(f.excursion_points)};v.reason=[`Extreme ${fmt(v.anchor.price,0)} · ${v.anchor.priceSource==='physical_seq'?'原始 _seq 精準價':'事件價位'}`,`離 Value boundary ${fmt(v.metrics.excursion)} pts`];return finish(v)}
 if(id==='MR_REJECTION'){const a={time:ms(c.extremeTime||c.extreme_time),price:num(c.extremePrice,c.extreme_price)},d=decision(c,bars,id,c.clearReclaimTime||c.clear_reclaim_time,c.clearReclaimPrice||c.clear_reclaim_price);const t=secs(c.extremeTime||c.extreme_time,c.clearReclaimTime||c.clear_reclaim_time),depth=d.price!=null&&b!=null?(side==='down'?d.price-b:b-d.price):null;v.points=[a,d].filter(x=>x.time!=null&&x.price!=null);v.anchor=d;v.reference={price:b,label:'Reclaim boundary'};v.metrics={reclaimSeconds:t,reclaimDepth:depth};v.reason=v.answer?[`Extreme → Reclaim ${fmt(t)}s（限制 ≤ 60s）`,`回到 Value 內 ${fmt(depth)} pts`]:[`尚未形成合格 Rejection`,`截至判定點未同時滿足速度與深度；轉看 Acceptance`];return finish(v)}
 if(id==='MR_CLEAR_RECLAIM'){const d=decision(c,bars,id,c.clearReclaimTime||c.clear_reclaim_time,c.clearReclaimPrice||c.clear_reclaim_price);const width=num(p.width,c.value_width)||0,need=Math.max(3,width*.08),threshold=b==null?null:(side==='down'?b+need:b-need),actual=d.price!=null&&b!=null?(side==='down'?d.price-b:b-d.price):null,t=secs(c.extremeTime||c.extreme_time,c.clearReclaimTime||c.clear_reclaim_time);v.anchor=d;v.reference={price:threshold,label:'Clear Reclaim threshold'};v.metrics={requiredDepth:need,actualDepth:actual,reclaimSeconds:t,actualPrice:d.price};v.reason=[`深度：實際 ${fmt(actual)} pts vs 需求 ≥ ${fmt(need)} pts`,`速度：實際 ${fmt(t)}s vs 上限 60s`,`Decision price ${fmt(d.price,0)}${d.priceSource==='physical_seq'?' · physical _seq':''}`];return finish(v)}
 if(id==='MR_RECLAIM_LEG'){const a={time:ms(c.extremeTime||c.extreme_time),price:num(c.extremePrice,c.extreme_price)},d=decision(c,bars,id,c.turnConfirmTime||c.turn_confirm_time),leg=num(f.leg_points);v.points=[a,d].filter(x=>x.time!=null&&x.price!=null);v.anchor=d;v.metrics={legPoints:leg,turnConfirm:8};v.reason=[`Reclaim Leg ${fmt(leg)} pts`,`Turn Confirmation：反向 8 pts 後才鎖定 Leg，避免事後看完整段才畫 Profile`];return finish(v)}
 if(id==='MR_LVN'||id==='BO_LVN'){const d=decision(c,bars,id,c.turnConfirmTime||c.turn_confirm_time,c.lvn),depth=num(f.lvn_depth);v.anchor={...d,price:num(c.lvn,d.price)};if(c.lvn!=null)v.range={startTime:d.time||first,endTime:last,low:Number(c.lvn)-tol,high:Number(c.lvn)+tol};v.reference={price:num(c.lvn),label:'LVN'};v.metrics={lvn:num(c.lvn),depth,tolerance:tol};v.reason=c.lvn!=null?[`Valley LVN ${fmt(c.lvn,0)}`,`Valley depth ${pct(depth)} vs 需求 ≥ 55%`,`Touch tolerance ±${fmt(tol)} pt`]:[`未找到合格 Valley LVN`,`需求：Valley depth ≥ 55%，且位於合格 Value 區域`];return finish(v)}
 if(id==='MR_PULLBACK'||id==='BO_PULLBACK'){const d=decision(c,bars,id,c.entryTime||c.entry_time,c.entryPrice||c.entry_price),delay=secs(c.turnConfirmTime||c.turn_confirm_time,d.time);v.anchor=d;if(c.lvn!=null)v.range={startTime:ms(c.turnConfirmTime||c.turn_confirm_time)||first,endTime:d.time||last,low:Number(c.lvn)-tol,high:Number(c.lvn)+tol};v.reference={price:num(c.lvn),label:'Pullback Location'};v.metrics={delaySeconds:delay,tolerance:tol};v.reason=v.answer?[`第一次合法回到已知 LVN ±${fmt(tol)} pt`,`Leg Confirm → Pullback ${fmt(delay)}s（上限 120s）`]:[`尚未出現合法 First Pullback / 已錯過第一測`,`最長等待 120s；第二、第三次測試不視為同一品質`];return finish(v)}
 if(id==='MR_ENTRY'||id==='BO_ENTRY'){const d=decision(c,bars,id,c.entryTime||c.entry_time,c.entryPrice||c.entry_price);v.anchor=d;v.trade={entry:num(c.entryPrice,c.entry_price,d.price),stop:num(c.stop),target:num(c.target),direction:c.direction};const risk=v.trade.entry!=null&&v.trade.stop!=null?Math.abs(v.trade.entry-v.trade.stop):null,reward=v.trade.entry!=null&&v.trade.target!=null?Math.abs(v.trade.target-v.trade.entry):null,r= risk>0?reward/risk:null;v.metrics={risk,reward,r};v.reason=v.answer?[`Entry ${fmt(v.trade.entry,0)} / Stop ${fmt(v.trade.stop,0)} / Target ${fmt(v.trade.target,1)}`,`Risk ${fmt(risk)} pts · Reward ${fmt(reward)} pts · ${r==null?'—':fmt(r,2)+'R'}`]:[`Setup 存在，但目前執行品質不合格`,`不因為方向看對就追價或擴大 Stop`];return finish(v)}
 if(id==='BO_ACCEPTANCE'){const d=decision(c,bars,id,meta(c,id)?.decision_time||c.extremeTime||c.extreme_time),outside=num(f.outside_ratio),dispPct=num(f.acceptance_displacement_pct),disp=num(f.acceptance_displacement);v.anchor=d;v.range={startTime:ms(c.attemptStartTime||c.attempt_start_time)||first,endTime:d.time||last,low:side==='down'?num(c.extremePrice,c.extreme_price):b,high:side==='down'?b:num(c.extremePrice,c.extreme_price)};v.reference={price:b,label:'Old Value boundary'};v.metrics={outsideRatio:outside,displacement:disp,displacementPct:dispPct};v.reason=v.answer?[`Value 外停留 ${pct(outside)} vs 需求 ≥ 70%`,`Displacement ${fmt(disp)} pts · ${pct(dispPct)} VW（需求 ≥ 20% VW）`]:[`Acceptance 尚未成立`,`Outside ${pct(outside)} / Displacement ${pct(dispPct)} VW；不夠就維持 WAIT`];return finish(v)}
 if(id==='BO_DISPLACEMENT'||id==='BO_IMPULSE_LEG'){const a={time:ms(c.attemptStartTime||c.attempt_start_time),price:b},d=decision(c,bars,id,meta(c,id)?.decision_time||c.turnConfirmTime||c.turn_confirm_time||c.extremeTime||c.extreme_time),leg=num(f.leg_points),disp=num(f.acceptance_displacement),dispPct=num(f.acceptance_displacement_pct);v.points=[a,d].filter(x=>x.time!=null&&x.price!=null);v.anchor=d;v.metrics={legPoints:leg,displacement:disp,displacementPct:dispPct};v.reason=id==='BO_DISPLACEMENT'?[`Displacement ${fmt(disp)} pts · ${pct(dispPct)} VW`,`要的是有效重新定價，不是只高/低出 Value 1 tick`]:[`Impulse Leg ${fmt(leg)} pts`,`Accepted Breakout 後等待因果 Turn Confirm，再建立 Leg Profile`];return finish(v)}
 if(id==='BO_RESPONSE'){const d=decision(c,bars,id,c.entryTime||c.entry_time,c.entryPrice||c.entry_price);v.anchor=d;v.reference={price:num(c.lvn),label:'LVN'};v.metrics={responseThreshold:2};v.reason=v.answer?[`Pullback 停止逆向發展並重新順突破推進`,`目前 Response 門檻 ≥ 2 pts`]:[`尚未看到足夠 Response Confirmation`,`確認太晚也會犧牲 Entry / Reward，後續研究保留這個 trade-off`];return finish(v)}
 if(id==='WAIT_AMBIGUOUS'||id==='NO_TRADE'){const d=decision(c,bars,id,meta(c,id)?.decision_time||c.extremeTime||c.extreme_time,c.extremePrice||c.extreme_price);v.anchor=d;v.reason=[id==='WAIT_AMBIGUOUS'?`Rejection / Acceptance 都尚未確認：WAIT 是正式狀態`:`結構、位置或執行條件觸發一票否決：不交易`];return finish(v)}
 v.anchor=decision(c,bars,id,meta(c,id)?.decision_time||c.extremeTime||c.extreme_time,c.extremePrice||c.extreme_price);return finish(v)
}
function all(c,bars){return Object.keys(c?.nodes||{}).filter(id=>FabioV2.nodeMap?.[id]).map(id=>resolve(c,bars,id))}
FabioV3.nodeVisuals={resolve,all,nearest,meta};
})();
