window.FabioV3=window.FabioV3||{};
(()=>{
const R=()=>FabioV3.visualRegistry;
const num=(...v)=>{for(const x of v){const n=Number(x);if(Number.isFinite(n))return n}return null};
const ms=v=>{if(v==null)return null;const n=typeof v==='number'?v:Date.parse(v);return Number.isFinite(n)?n:null};
const truth=(c,id)=>Boolean(c?.nodes?.[id]);
function meta(c,id){return c?.nodeMeta?.[id]||c?.node_meta?.[id]||null}
function nearest(bars,time){const t=ms(time);if(!bars?.length||t==null)return null;let lo=0,hi=bars.length-1;while(lo<hi){const m=(lo+hi)>>1;if(bars[m].timestamp<t)lo=m+1;else hi=m}const a=bars[lo],b=bars[Math.max(0,lo-1)];return !b||Math.abs(a.timestamp-t)<=Math.abs(b.timestamp-t)?a:b}
function decision(c,bars,id,fallbackTime,fallbackPrice){const m=meta(c,id),time=m?.decision_time||m?.time||fallbackTime;const bar=nearest(bars,time);return{time:ms(time??bar?.timestamp),price:num(m?.decision_price,m?.price,fallbackPrice,bar?.close),seq:num(m?.decision_seq,m?.seq,bar?.lastSeq)}}
function boundary(c){const p=c.priorProfile||{},f=c.features||{},side=f.auction_side;return side==='down'?num(p.val,c.val):num(p.vah,c.vah)}
function base(c,id){const cfg=R().spec(id);return{nodeId:id,code:FabioV2.nodeMap?.[id]?.code||id,label:cfg.label,family:cfg.family,layer:cfg.layer,tone:cfg.tone,answer:truth(c,id),metrics:{},reason:[]}}
function finish(v){v.style=R().style(v.nodeId,v.answer);return v}
function resolve(c,bars,id){const v=base(c,id),p=c.priorProfile||{},f=c.features||{},first=bars?.[0]?.timestamp,last=bars?.at(-1)?.timestamp,b=boundary(c),tol=num(f.lvn_tolerance,1)??1;
 if(id==='CTX_VALUE'){v.range={startTime:first,endTime:last,low:num(p.val,c.val),high:num(p.vah,c.vah)};v.lines=[{price:num(p.vah,c.vah),label:'VAH'},{price:num(p.poc,c.poc),label:'POC'},{price:num(p.val,c.val),label:'VAL'}];v.reason=[`Value Width ${num(p.width,c.value_width)??'—'} pts`];return finish(v)}
 if(id==='AUC_ATTEMPT'){v.anchor=decision(c,bars,id,c.attemptStartTime||c.attempt_start_time,b);v.reference={price:b,label:f.auction_side==='down'?'VAL':'VAH'};v.metrics={excursion:num(f.excursion_points),threshold:num(f.excursion_threshold)};v.reason=[`Excursion ${v.metrics.excursion??'—'} pts`,`門檻 ${v.metrics.threshold??'—'} pts`];return finish(v)}
 if(id==='AUC_EXTREME'){v.anchor=decision(c,bars,id,c.extremeTime||c.extreme_time,c.extremePrice||c.extreme_price);v.reference={price:b,label:'Value boundary'};v.reason=[`Extreme ${v.anchor.price??'—'}`,`Excursion ${num(f.excursion_points)??'—'} pts`];return finish(v)}
 if(id==='MR_REJECTION'){const a={time:ms(c.extremeTime||c.extreme_time),price:num(c.extremePrice,c.extreme_price)},d=decision(c,bars,id,c.clearReclaimTime||c.clear_reclaim_time,c.clearReclaimPrice||c.clear_reclaim_price);v.points=[a,d].filter(x=>x.time!=null&&x.price!=null);v.anchor=d;v.reference={price:b,label:'Reclaim boundary'};v.reason=v.answer?['價格從 Extreme 快速返回舊 Value']:['尚未形成合格 Rejection；繼續檢查 Acceptance'];return finish(v)}
 if(id==='MR_CLEAR_RECLAIM'){const d=decision(c,bars,id,c.clearReclaimTime||c.clear_reclaim_time,c.clearReclaimPrice||c.clear_reclaim_price);const width=num(p.width,c.value_width)||0,need=Math.max(3,width*.08),side=f.auction_side,threshold=b==null?null:(side==='down'?b+need:b-need);v.anchor=d;v.reference={price:threshold,label:'Clear Reclaim threshold'};v.metrics={requiredDepth:need,actualPrice:d.price};v.reason=[`要求深入 Value ≥ ${need.toFixed(1)} pts`,`限制時間 ≤ 60s`];return finish(v)}
 if(id==='MR_RECLAIM_LEG'){const a={time:ms(c.extremeTime||c.extreme_time),price:num(c.extremePrice,c.extreme_price)},d=decision(c,bars,id,c.turnConfirmTime||c.turn_confirm_time);v.points=[a,d].filter(x=>x.time!=null&&x.price!=null);v.anchor=d;v.reason=['Extreme → 因果 Turn Confirm','Leg 完成後才允許建立 Volume Profile'];return finish(v)}
 if(id==='MR_LVN'||id==='BO_LVN'){const d=decision(c,bars,id,c.turnConfirmTime||c.turn_confirm_time,c.lvn);v.anchor={...d,price:num(c.lvn,d.price)};if(c.lvn!=null)v.range={startTime:d.time||first,endTime:last,low:Number(c.lvn)-tol,high:Number(c.lvn)+tol};v.reference={price:num(c.lvn),label:'LVN'};v.reason=c.lvn!=null?[`LVN ${c.lvn}`,`Touch tolerance ±${tol}`]:['未找到合格 Valley LVN'];return finish(v)}
 if(id==='MR_PULLBACK'||id==='BO_PULLBACK'){const d=decision(c,bars,id,c.entryTime||c.entry_time,c.entryPrice||c.entry_price);v.anchor=d;if(c.lvn!=null)v.range={startTime:ms(c.turnConfirmTime||c.turn_confirm_time)||first,endTime:d.time||last,low:Number(c.lvn)-tol,high:Number(c.lvn)+tol};v.reference={price:num(c.lvn),label:'Pullback Location'};v.reason=v.answer?['第一次合法回到已知 LVN']:['尚未出現合法 First Pullback / 已錯過第一測'];return finish(v)}
 if(id==='MR_ENTRY'||id==='BO_ENTRY'){const d=decision(c,bars,id,c.entryTime||c.entry_time,c.entryPrice||c.entry_price);v.anchor=d;v.trade={entry:num(c.entryPrice,c.entry_price,d.price),stop:num(c.stop),target:num(c.target),direction:c.direction};v.reason=v.answer?['Location、Stop、Target 仍符合策略品質']:['Setup 存在，但目前執行品質不合格'];return finish(v)}
 if(id==='BO_ACCEPTANCE'){const d=decision(c,bars,id,meta(c,id)?.decision_time||c.extremeTime||c.extreme_time);v.anchor=d;v.range={startTime:ms(c.attemptStartTime||c.attempt_start_time)||first,endTime:d.time||last,low:f.auction_side==='down'?num(c.extremePrice,c.extreme_price):b,high:f.auction_side==='down'?b:num(c.extremePrice,c.extreme_price)};v.reference={price:b,label:'Old Value boundary'};v.reason=v.answer?['Value 外持續成交，沒有快速 Clear Reclaim']:['Acceptance 尚未成立'];return finish(v)}
 if(id==='BO_DISPLACEMENT'||id==='BO_IMPULSE_LEG'){const a={time:ms(c.attemptStartTime||c.attempt_start_time),price:b},d=decision(c,bars,id,meta(c,id)?.decision_time||c.turnConfirmTime||c.turn_confirm_time||c.extremeTime||c.extreme_time);v.points=[a,d].filter(x=>x.time!=null&&x.price!=null);v.anchor=d;v.reason=[id==='BO_DISPLACEMENT'?'突破必須有有效單方向位移':'Accepted Breakout 後的因果推進腿'];return finish(v)}
 if(id==='BO_RESPONSE'){const d=decision(c,bars,id,c.entryTime||c.entry_time,c.entryPrice||c.entry_price);v.anchor=d;v.reference={price:num(c.lvn),label:'LVN'};v.reason=v.answer?['Pullback 停止逆向發展並重新順突破推進']:['尚未看到足夠 Response Confirmation'];return finish(v)}
 if(id==='WAIT_AMBIGUOUS'||id==='NO_TRADE'){const d=decision(c,bars,id,meta(c,id)?.decision_time||c.extremeTime||c.extreme_time,c.extremePrice||c.extreme_price);v.anchor=d;v.reason=[id==='WAIT_AMBIGUOUS'?'Rejection / Acceptance 都尚未確認':'結構、位置或執行條件觸發一票否決'];return finish(v)}
 v.anchor=decision(c,bars,id,meta(c,id)?.decision_time||c.extremeTime||c.extreme_time,c.extremePrice||c.extreme_price);return finish(v)
}
function all(c,bars){return Object.keys(c?.nodes||{}).filter(id=>FabioV2.nodeMap?.[id]).map(id=>resolve(c,bars,id))}
FabioV3.nodeVisuals={resolve,all,nearest,meta};
})();
