window.FabioV3=window.FabioV3||{};
(()=>{
let activeLayer=null;
const valid=n=>Number.isFinite(Number(n));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
class DecisionPixiLayer{
 constructor(el,chart,c,bars,opts={}){this.el=el;this.chart=chart;this.case=c;this.bars=bars;this.opts=opts;this.app=null;this.activeNode=null;this.mode=opts.visualMode||'teaching';this.raf=0;this.handlers=[];this.ro=null;this.visuals=[]}
 async init(){if(!window.PIXI||!this.el||!this.chart)return this;this.el.style.position='relative';const old=this.el.querySelector('.decision-pixi-canvas');if(old)old.remove();const app=new PIXI.Application();await app.init({resizeTo:this.el,backgroundAlpha:0,antialias:true,autoDensity:true,resolution:Math.min(2,window.devicePixelRatio||1),preference:'webgl'});this.app=app;app.canvas.className='decision-pixi-canvas';Object.assign(app.canvas.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none',zIndex:'8'});this.el.appendChild(app.canvas);this.visuals=FabioV3.nodeVisuals.all(this.case,this.bars);this.bind();this.redraw();window.__FABIO_PIXI__=this;return this}
 bind(){const redraw=()=>this.schedule();for(const type of ['onZoom','onScroll','onVisibleRangeChange','onPaneDrag']){try{this.chart.subscribeAction(type,redraw);this.handlers.push([type,redraw])}catch{}}this.ro=new ResizeObserver(()=>this.schedule());this.ro.observe(this.el)}
 schedule(){cancelAnimationFrame(this.raf);this.raf=requestAnimationFrame(()=>this.redraw())}
 destroy(){cancelAnimationFrame(this.raf);for(const [t,h] of this.handlers){try{this.chart?.unsubscribeAction(t,h)}catch{}}this.handlers=[];this.ro?.disconnect();this.ro=null;try{this.app?.destroy(true)}catch{}this.app=null;if(activeLayer===this)activeLayer=null}
 point(time,price){if(time==null||price==null)return null;try{const p=this.chart.convertToPixel({timestamp:Number(time),value:Number(price)},{paneId:'candle_pane'});return valid(p?.x)&&valid(p?.y)?{x:Number(p.x),y:Number(p.y)}:null}catch{return null}}
 x(time){if(time==null)return null;try{const p=this.chart.convertToPixel({timestamp:Number(time)},{paneId:'candle_pane'});return valid(p?.x)?Number(p.x):null}catch{return null}}
 y(price){if(price==null)return null;try{const p=this.chart.convertToPixel({value:Number(price)},{paneId:'candle_pane'});return valid(p?.y)?Number(p.y):null}catch{return null}}
 label(text,x,y,color,bg=0x07101b,size=11){if(!this.app||x==null||y==null)return;const padX=6,padY=3;const t=new PIXI.Text({text:String(text),style:{fontFamily:'Inter,system-ui,sans-serif',fontSize:size,fontWeight:'600',fill:color}});t.x=x+padX;t.y=y+padY;const g=new PIXI.Graphics();g.roundRect(x,y,t.width+padX*2,t.height+padY*2,5).fill({color:bg,alpha:.9}).stroke({color,alpha:.55,width:1});this.app.stage.addChild(g,t);return{g,t}}
 line(y,color,alpha=.65,width=1,dash=false){if(y==null||!this.app)return;const w=this.app.screen.width,g=new PIXI.Graphics();if(dash){for(let x=0;x<w;x+=10)g.moveTo(x,y).lineTo(Math.min(w,x+5),y)}else g.moveTo(0,y).lineTo(w,y);g.stroke({color,alpha,width});this.app.stage.addChild(g)}
 drawReference(v){if(!v.reference||v.reference.price==null)return;const y=this.y(v.reference.price);if(y==null)return;this.line(y,v.style.line,.34,1,true);if(this.activeNode===v.nodeId)this.label(`${v.reference.label} ${Number(v.reference.price).toLocaleString()}`,8,clamp(y-22,4,this.app.screen.height-28),v.style.text)}
 drawBand(v){const r=v.range;if(!r||r.low==null||r.high==null)return;const x1=this.x(r.startTime??this.bars[0]?.timestamp),x2=this.x(r.endTime??this.bars.at(-1)?.timestamp),y1=this.y(r.high),y2=this.y(r.low);if([x1,x2,y1,y2].some(x=>x==null))return;const left=Math.min(x1,x2),top=Math.min(y1,y2),w=Math.max(2,Math.abs(x2-x1)),h=Math.max(2,Math.abs(y2-y1)),a=this.activeNode===v.nodeId?Math.max(.22,v.style.fillAlpha*2):v.style.fillAlpha;const g=new PIXI.Graphics();g.rect(left,top,w,h).fill({color:v.style.fill,alpha:a}).stroke({color:v.style.line,alpha:this.activeNode===v.nodeId?.95:.5,width:this.activeNode===v.nodeId?2.5:1});this.app.stage.addChild(g);if(this.activeNode===v.nodeId)this.label(`${v.code} ${v.label}`,left+6,Math.max(4,top+5),v.style.text,v.style.fill)}
 drawMarker(v,extreme=false){const a=v.anchor,p=this.point(a?.time,a?.price);if(!p)return;const active=this.activeNode===v.nodeId,r=active?8:5,g=new PIXI.Graphics();if(extreme){g.moveTo(p.x,p.y-r-3).lineTo(p.x-r,p.y+r).lineTo(p.x+r,p.y+r).closePath().fill({color:v.style.fill,alpha:.92}).stroke({color:v.style.line,width:active?3:2,alpha:1})}else{g.circle(p.x,p.y,r).fill({color:v.style.fill,alpha:.92}).stroke({color:v.style.line,width:active?3:2,alpha:1});g.moveTo(p.x-10,p.y).lineTo(p.x+10,p.y).moveTo(p.x,p.y-10).lineTo(p.x,p.y+10).stroke({color:v.style.line,width:1,alpha:.6})}this.app.stage.addChild(g);this.drawReference(v);if(active)this.label(`${v.code} ${v.label} · ${Number(a.price).toLocaleString()}`,p.x+10,clamp(p.y-30,4,this.app.screen.height-30),v.style.text,v.style.fill,12)}
 drawPath(v){const pts=(v.points||[]).map(x=>this.point(x.time,x.price)).filter(Boolean);if(pts.length<2){this.drawMarker(v);return}const active=this.activeNode===v.nodeId,g=new PIXI.Graphics();g.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)g.lineTo(pts[i].x,pts[i].y);g.stroke({color:v.style.line,width:active?3.5:2,alpha:active?1:.75});const a=pts.at(-1),b=pts.at(-2),ang=Math.atan2(a.y-b.y,a.x-b.x),s=active?9:7;g.moveTo(a.x,a.y).lineTo(a.x-Math.cos(ang-.55)*s,a.y-Math.sin(ang-.55)*s).moveTo(a.x,a.y).lineTo(a.x-Math.cos(ang+.55)*s,a.y-Math.sin(ang+.55)*s).stroke({color:v.style.line,width:active?3:2,alpha:1});this.app.stage.addChild(g);this.drawReference(v);if(active)this.label(`${v.code} ${v.label}`,a.x+8,clamp(a.y-28,4,this.app.screen.height-30),v.style.text,v.style.fill,12)}
 drawRange(v){this.drawBand(v);this.drawReference(v);if(v.anchor)this.drawMarker(v)}
 drawTrade(v){const a=v.anchor,p=this.point(a?.time,a?.price);if(!p)return;const active=this.activeNode===v.nodeId,g=new PIXI.Graphics(),long=(v.trade?.direction||this.case.direction)==='long',s=active?11:9;if(long){g.moveTo(p.x,p.y-s).lineTo(p.x-s,p.y+s).lineTo(p.x+s,p.y+s)}else{g.moveTo(p.x,p.y+s).lineTo(p.x-s,p.y-s).lineTo(p.x+s,p.y-s)}g.closePath().fill({color:v.style.fill,alpha:.95}).stroke({color:v.style.line,width:2});this.app.stage.addChild(g);for(const [key,label] of [['stop','STOP'],['target','TARGET']]){const price=v.trade?.[key];if(price==null)continue;const y=this.y(price);this.line(y,key==='stop'?0xff6378:0x3de6aa,.55,1,true);if(active)this.label(`${label} ${Number(price).toLocaleString()}`,8,clamp(y-20,4,this.app.screen.height-26),key==='stop'?0xffa4b0:0xa9ffdf)}if(active)this.label(`${v.code} ${v.label} ${Number(a.price).toLocaleString()}`,p.x+12,clamp(p.y-30,4,this.app.screen.height-30),v.style.text,v.style.fill,12)}
 drawBadge(v){const a=v.anchor,p=this.point(a?.time,a?.price);if(!p)return;const active=this.activeNode===v.nodeId;this.label(`${v.code} · ${v.answer?v.label:'NO '+v.label}`,p.x+8,clamp(p.y-25,4,this.app.screen.height-30),v.style.text,v.style.fill,active?13:11);this.drawReference(v)}
 shouldDraw(v){if(this.mode==='blind')return this.activeNode===v.nodeId;if(this.mode==='single')return this.activeNode===v.nodeId;if(this.mode==='structure')return['context','auction','mr','bo','location','decision'].includes(v.layer);if(this.mode==='trade')return v.layer==='trade'||v.layer==='location';return true}
 redraw(){if(!this.app)return;this.app.stage.removeChildren().forEach(x=>x.destroy?.({children:true}));for(const v of this.visuals){if(!this.shouldDraw(v))continue;switch(v.family){case'context_band':this.drawBand(v);(v.lines||[]).forEach(x=>{const y=this.y(x.price);this.line(y,v.style.line,.25,1,true);if(this.activeNode===v.nodeId&&y!=null)this.label(`${x.label} ${Number(x.price).toLocaleString()}`,8,clamp(y-19,3,this.app.screen.height-24),v.style.text)});break;case'extreme_marker':this.drawMarker(v,true);break;case'trigger_marker':this.drawMarker(v);break;case'structure_path':this.drawPath(v);break;case'range_box':this.drawRange(v);break;case'trade_marker':this.drawTrade(v);break;default:this.drawBadge(v)}}}
 setMode(mode){this.mode=mode||'teaching';this.redraw();return this}
 focus(nodeId,{scroll=true}={}){this.activeNode=nodeId;const v=this.visuals.find(x=>x.nodeId===nodeId);if(scroll&&v?.anchor?.time){try{this.chart.scrollToTimestamp(Number(v.anchor.time),250)}catch{}setTimeout(()=>this.redraw(),280)}else this.redraw();return v}
 clearFocus(){this.activeNode=null;this.redraw()}
 getVisual(nodeId){return this.visuals.find(x=>x.nodeId===nodeId)||null}
}
async function mount(el,chart,c,bars,opts={}){if(activeLayer)activeLayer.destroy();const layer=new DecisionPixiLayer(el,chart,c,bars,opts);activeLayer=layer;await layer.init();return layer}
function current(){return activeLayer}
FabioV3.pixi={mount,current,DecisionPixiLayer};
})();
