window.FabioV3=window.FabioV3||{};
(()=>{
let selectedNode=null,lastRoute='',enhanceQueued=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmtTime=t=>{if(t==null)return'—';try{return new Date(Number(t)).toLocaleTimeString('zh-TW',{hour12:false,timeZone:'Asia/Taipei'})}catch{return'—'}};
const fmtPrice=n=>Number.isFinite(Number(n))?Number(n).toLocaleString():'—';
function familyLabel(f){return({context_band:'區域',trigger_marker:'觸發',extreme_marker:'極值',structure_path:'路徑',range_box:'區間',trade_marker:'交易',decision_badge:'判定'})[f]||f}
function modeButtons(){return`<div class="visual-modebar" id="visualModebar"><button data-vmode="teaching">全部決策</button><button data-vmode="single">目前節點</button><button data-vmode="blind">隱藏標記</button></div>`}
function setActiveMode(mode){$$('[data-vmode]').forEach(b=>b.classList.toggle('active',b.dataset.vmode===mode))}
function detail(v){let box=$('#nodeVisualDetail');if(!box)return;if(!v){box.className='node-visual-detail empty';box.textContent='點右側任一 Decision Node，即可在 K 線精準定位它的觸發點、區域或結構路徑。';return}const anchor=v.anchor||{},range=v.range;box.className='node-visual-detail';box.innerHTML=`<div class="v-head"><div><span>${v.code}</span><b>${v.label}</b></div><em class="family">${familyLabel(v.family)}</em></div><div class="v-anchor"><div><span>定位時間</span><b>${fmtTime(anchor.time||range?.endTime)}</b></div><div><span>${range?'價格區域':'觸發價位'}</span><b>${range?`${fmtPrice(range.low)} – ${fmtPrice(range.high)}`:fmtPrice(anchor.price)}</b></div></div><ul>${(v.reason||[]).map(x=>`<li>${String(x)}</li>`).join('')||'<li>此節點目前只有結構定位資料。</li>'}</ul>`}
function getLayer(){return FabioV3.pixi?.current?.()||null}
function focusNode(id,{scroll=true,mode='single'}={}){selectedNode=id;const layer=getLayer();if(!layer)return null;if(mode)layer.setMode(mode);const v=layer.focus(id,{scroll});$$('.visual-node-row').forEach(b=>b.classList.toggle('focused',b.dataset.nodeId===id));setActiveMode(layer.mode);detail(v);return v}
function enhanceReplay(){const outcomes=$('.node-outcomes'),toolbar=$('.replay-toolbar');if(!outcomes||!toolbar)return;if(!$('#visualModebar'))toolbar.insertAdjacentHTML('beforeend',modeButtons());for(const b of $$('.node-outcomes button')){if(b.classList.contains('visual-node-row'))continue;const go=b.dataset.go||'',id=go.startsWith('nodes/')?go.slice(6):null;if(!id)continue;const spec=FabioV3.visualRegistry?.spec(id);b.classList.add('visual-node-row');b.dataset.nodeId=id;b.dataset.visual=familyLabel(spec?.family);b.title=`定位 ${FabioV2.nodeMap?.[id]?.code||id} 到 K 線`}
 if(!$('#nodeVisualDetail'))outcomes.insertAdjacentHTML('afterend','<div id="nodeVisualDetail" class="node-visual-detail empty">點右側任一 Decision Node，即可在 K 線精準定位它的觸發點、區域或結構路徑。</div><p class="visual-hint">PixiJS Visual Layer：點節點會自動捲動到 Decision Time；拖曳與縮放 KLineChart 時標記會同步重算。</p>');
 const layer=getLayer();if(layer)setActiveMode(layer.mode)
}
function enhancePractice(){const tools=$('.practice-tools');if(tools&&!tools.querySelector('.practice-visual-state'))tools.insertAdjacentHTML('beforeend','<span class="practice-visual-state">答題前：裸圖 · 答題後：揭露 Decision Visuals</span>')}
function ensureLogoBase(small){let base=[...small.childNodes].find(n=>n.nodeType===3);if(!base){base=document.createTextNode('');small.insertBefore(base,small.firstChild)}if(base.nodeValue!=='Binary Decision Training · V3')base.nodeValue='Binary Decision Training · V3'}
function enhanceChrome(){const small=$('.logo small');if(small)ensureLogoBase(small);const header=$('.header-actions');if(header&&!header.querySelector('.pixi-pill'))header.insertAdjacentHTML('afterbegin','<span class="pill pixi-pill">PixiJS 8.19.0</span>')}
function enhance(){enhanceChrome();const r=location.hash.replace(/^#\/?/,'').split('/')[0]||'dashboard';if(r==='replay')enhanceReplay();if(r==='practice')enhancePractice();lastRoute=r}
function scheduleEnhance(){if(enhanceQueued)return;enhanceQueued=true;requestAnimationFrame(()=>{enhanceQueued=false;enhance()})}
document.addEventListener('click',e=>{const node=e.target.closest?.('.node-outcomes button.visual-node-row');if(node){e.preventDefault();e.stopImmediatePropagation();focusNode(node.dataset.nodeId,{scroll:true,mode:'single'});return}const vm=e.target.closest?.('[data-vmode]');if(vm){e.preventDefault();e.stopImmediatePropagation();const layer=getLayer();if(!layer)return;const mode=vm.dataset.vmode;if(mode==='blind'){selectedNode=null;layer.clearFocus();layer.setMode('blind');$$('.visual-node-row').forEach(b=>b.classList.remove('focused'));detail(null)}else if(mode==='single'){const id=selectedNode||$('.visual-node-row')?.dataset.nodeId;if(id)focusNode(id,{scroll:false,mode:'single'})}else{layer.setMode('teaching');setActiveMode('teaching')}return}const reveal=e.target.closest?.('.replay-toolbar [data-reveal]');if(reveal){e.preventDefault();e.stopImmediatePropagation();const layer=getLayer();if(!layer)return;const v=reveal.dataset.reveal;if(v==='none'){selectedNode=null;layer.clearFocus();layer.setMode('blind');detail(null)}else if(v==='structure'){layer.setMode('structure')}else{layer.setMode('teaching')}setActiveMode(layer.mode)}},true);
document.addEventListener('pointerover',e=>{const node=e.target.closest?.('.visual-node-row');if(!node||selectedNode===node.dataset.nodeId)return;const layer=getLayer();if(!layer||layer.mode==='blind')return;layer.focus(node.dataset.nodeId,{scroll:false});detail(layer.getVisual(node.dataset.nodeId))});
document.addEventListener('pointerout',e=>{const node=e.target.closest?.('.visual-node-row');if(!node)return;const layer=getLayer();if(!layer)return;if(selectedNode)layer.focus(selectedNode,{scroll:false});else{layer.clearFocus();detail(null)}});
const mo=new MutationObserver(scheduleEnhance);mo.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('hashchange',()=>setTimeout(enhance,0));setTimeout(enhance,300);
FabioV3.visualUI={focusNode,enhance,get selectedNode(){return selectedNode}};
})();
