window.FabioV2=window.FabioV2||{};
(()=>{
let chart=null;const remoteBars=new Map();
function ensureLocale(){if(window.klinecharts?.registerLocale)klinecharts.registerLocale('zh-TW',{time:'時間：',open:'開：',high:'高：',low:'低：',close:'收：',volume:'量：',change:'漲跌：',turnover:'成交額：',second:'秒',minute:'分鐘',hour:'小時',day:'天',week:'週',month:'月',year:'年'})}
function secondBarsForCase(c){const s=window.__SECOND_BARS__;if(!s?.rows||s.date!==c.date)return null;const keys=['timestamp','open','high','low','close','volume','firstSeq','lastSeq'];return s.rows.map(r=>Object.fromEntries(keys.map((k,i)=>[k,r[i]])))}
function minuteBarsForCase(c){return window.__REPLAY_DATA__?.sessions?.[c.date]?.bars||[]}
function barsRaw(c){return remoteBars.get(c.id)||secondBarsForCase(c)||minuteBarsForCase(c)}
function getBars(c,windowMs=900000){const bars=barsRaw(c)||[];if(!bars.length)return[];const start=Date.parse(c.attemptStartTime||c.attempt_start_time||c.extremeTime||c.extreme_time||c.entryTime||c.entry_time||new Date(bars[0].timestamp).toISOString());return bars.filter(b=>b.timestamp>=start-windowMs*.25&&b.timestamp<=start+windowMs)}
async function ensureBars(c){let bars=barsRaw(c);if(bars?.length)return bars;if(!FabioV2.store?.state?.apiOnline)return[];try{const r=await FabioV2.store.api('/replay/'+encodeURIComponent(c.id));bars=r?.bars||[];if(r?.case&&c)Object.assign(c,r.case);if(bars.length)remoteBars.set(c.id,bars);return bars}catch(e){console.warn('Replay API unavailable',e);return[]}}
function timeOnly(s){return s?String(s).slice(11,19):'—'}
function emitPixiMounted(layer,el,c,opts){try{window.dispatchEvent(new CustomEvent('fabio:pixi-mounted',{detail:{layer,element:el,caseId:c?.id,options:opts}}))}catch{}}
async function render(el,c,opts={}){ensureLocale();if(!el||!c)return;try{FabioV3?.pixi?.current?.()?.destroy?.()}catch{}el.innerHTML='<div class="empty-chart">載入 Replay…</div>';await ensureBars(c);const bars=getBars(c,opts.windowMs||900000);if(!bars.length){el.innerHTML='<div class="empty-chart">此案例尚未載入 Replay bars。請確認 Local Data API 與原始 Parquet 路徑。</div>';return}try{if(chart)klinecharts.dispose(el)}catch{};el.innerHTML='';chart=klinecharts.init(el,{locale:'zh-TW',timezone:'Asia/Taipei',styles:{grid:{horizontal:{color:'#1e2a3b'},vertical:{color:'#172333'}},candle:{bar:{upColor:'#27d3a2',downColor:'#ff6378',upBorderColor:'#27d3a2',downBorderColor:'#ff6378',upWickColor:'#27d3a2',downWickColor:'#ff6378'}}}});const localSec=Boolean(remoteBars.get(c.id)||secondBarsForCase(c));const period=localSec?{span:1,type:'second'}:{span:1,type:'minute'};chart.setSymbol({ticker:`MTX ${c.contract||c.expiry||'Replay'}`,pricePrecision:0,volumePrecision:0});chart.setPeriod(period);let cutoff=opts.cutoff?Date.parse(opts.cutoff):Infinity;const visible=bars.filter(b=>b.timestamp<=cutoff);chart.setDataLoader({getBars:({callback})=>callback(visible,{forward:false,backward:false})});try{chart.createIndicator('VOL',{pane:{height:72}})}catch{};setTimeout(async()=>{if(opts.legacyOverlays)drawLevels(chart,c,visible,opts);if(window.FabioV3?.pixi){const inferred=opts.visualMode||(opts.reveal?.length?'teaching':'blind');const layer=await FabioV3.pixi.mount(el,chart,c,visible,{...opts,visualMode:inferred});if(opts.focusNode)layer.focus(opts.focusNode,{scroll:false});emitPixiMounted(layer,el,c,opts)}},100);return{chart,bars,visible,period}}
function line(ch,bars,value,color,label){if(value==null||!bars.length)return;try{ch.createOverlay({name:'horizontalSegment',lock:true,points:[{timestamp:bars[0].timestamp,value:Number(value)},{timestamp:bars.at(-1).timestamp,value:Number(value)}],styles:{line:{color,size:1,style:'dashed'},text:{color}},extendData:{label}})}catch{}}
function marker(ch,time,value,label,color){if(!time||value==null)return;try{if(window.FabioOverlays?.marker)return window.FabioOverlays.marker(ch,{time,value:Number(value),label,side:'long',kind:'event',color});ch.createOverlay({name:'simpleAnnotation',points:[{timestamp:Date.parse(time),value:Number(value)}],extendData:label})}catch{}}
function drawLevels(ch,c,bars,opts){const p=c.priorProfile||window.__REPLAY_DATA__?.sessions?.[c.date]?.priorProfile||{};if(opts.showValue!==false){line(ch,bars,p.vah,'#ff7185','VAH');line(ch,bars,p.poc,'#f0bb55','POC');line(ch,bars,p.val,'#31d7a4','VAL')}if(opts.reveal?.includes('auction'))marker(ch,c.attemptStartTime||c.attempt_start_time,c.attemptStartPrice||c.extremePrice||c.extreme_price,'Auction','#58aaff');if(opts.reveal?.includes('extreme'))marker(ch,c.extremeTime||c.extreme_time,c.extremePrice||c.extreme_price,`Extreme ${timeOnly(c.extremeTime||c.extreme_time)}`,'#ff9b55');if(opts.reveal?.includes('reclaim')&&(c.clearReclaimTime||c.clear_reclaim_time))marker(ch,c.clearReclaimTime||c.clear_reclaim_time,c.clearReclaimPrice||c.clear_reclaim_price,'Clear Reclaim','#5dd8ff');if(opts.reveal?.includes('lvn'))line(ch,bars,c.lvn,'#a584ff','LVN');if(opts.reveal?.includes('trade')){marker(ch,c.entryTime||c.entry_time,c.entryPrice||c.entry_price,`ENTRY ${c.entryPrice??c.entry_price??''}`,'#39e5ab');line(ch,bars,c.stop,'#ff5f75','STOP');line(ch,bars,c.target,'#35d89d','TARGET')}}
FabioV2.chart={render,getBars,ensureBars,getInstance:()=>chart};
})();
