window.FabioV2=window.FabioV2||{};
(()=>{
const state={nodeId:null,filter:'all',limit:24,shuffle:false,selected:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function route(){const p=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);return{page:p[0],id:p[1]}}
function barsSvg(c,w=180,h=58){const a=FabioV2.chart?.getBars?.(c,240000)?.slice(-48)||[];if(!a.length)return'<span class="pl-no-preview">NO PREVIEW</span>';const lo=Math.min(...a.map(x=>x.low)),hi=Math.max(...a.map(x=>x.high)),d=Math.max(1,hi-lo);return`<svg viewBox="0 0 ${a.length*4} 50" preserveAspectRatio="none" width="${w}" height="${h}">${a.map((b,i)=>{const y1=4+(hi-b.high)/d*42,y2=4+(hi-b.low)/d*42,yo=4+(hi-b.open)/d*42,yc=4+(hi-b.close)/d*42,up=b.close>=b.open,cl=up?'pl-u':'pl-d';return`<line x1="${i*4+2}" y1="${y1}" x2="${i*4+2}" y2="${y2}" class="${cl}"/><rect x="${i*4+1}" y="${Math.min(yo,yc)}" width="2.6" height="${Math.max(1,Math.abs(yc-yo))}" class="${cl}"/>`}).join('')}</svg>`}
function cases(){let a=FabioV2.store?.casesForNode?.(state.nodeId)||[];if(state.filter==='yes')a=a.filter(c=>c.nodes?.[state.nodeId]===true);if(state.filter==='no')a=a.filter(c=>c.nodes?.[state.nodeId]===false);if(state.shuffle)a=[...a].sort(()=>Math.random()-.5);return a}
function tile(c){const ans=c.nodes?.[state.nodeId]===true;const chosen=state.selected.includes(c.id);return`<article class="pl-tile ${chosen?'selected':''}" data-id="${esc(c.id)}"><button class="pl-open" data-open="${esc(c.id)}"><div class="pl-chart">${barsSvg(c)}</div><div class="pl-meta"><b>${esc(c.date||c.trading_date)} · ${esc(c.strategy||'WAIT')}</b><span class="${ans?'yes':'no'}">${ans?'YES':'NO'}</span></div><small>${esc(c.id)}</small></button><button class="pl-compare ${chosen?'on':''}" data-compare="${esc(c.id)}" title="加入比較">${chosen?'✓':'⇄'}</button></article>`}
function render(){const host=document.querySelector('#patternLabGrid');if(!host)return;const all=cases(),show=all.slice(0,state.limit);const count=document.querySelector('#patternLabCount');if(count)count.textContent=`${all.length} cases · 顯示 ${show.length}`;host.innerHTML=show.map(tile).join('')||'<div class="empty">目前沒有符合的案例。啟動 Local API 掃描多年資料後會自動擴充。</div>';host.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>location.hash='#/replay/'+encodeURIComponent(b.dataset.open));host.querySelectorAll('[data-compare]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleCompare(b.dataset.compare)})}
function toggleCompare(id){const i=state.selected.indexOf(id);if(i>=0)state.selected.splice(i,1);else{if(state.selected.length>=2)state.selected.shift();state.selected.push(id)}render();if(state.selected.length===2)showCompare()}
function showCompare(){const pool=FabioV2.store.state.cases;const a=pool.find(x=>x.id===state.selected[0]),b=pool.find(x=>x.id===state.selected[1]);if(!a||!b)return;let modal=document.querySelector('#patternCompareModal');if(!modal){modal=document.createElement('div');modal.id='patternCompareModal';modal.className='pl-modal';document.body.appendChild(modal)};const pane=c=>`<div class="pl-compare-pane"><h3>${esc(c.date||c.trading_date)} · ${esc(c.strategy)} · ${c.direction==='long'?'多':'空'}</h3><div class="pl-big-chart">${barsSvg(c,520,220)}</div><p>${esc(c.id)}</p><button data-replay="${esc(c.id)}">完整 Replay</button></div>`;modal.innerHTML=`<div class="pl-modal-card"><div class="pl-modal-head"><div><b>Decision Pattern Compare</b><span>${esc(FabioV2.nodeMap?.[state.nodeId]?.title||state.nodeId)}</span></div><button id="plClose">✕</button></div><div class="pl-compare-grid">${pane(a)}${pane(b)}</div></div>`;modal.classList.add('open');modal.querySelector('#plClose').onclick=()=>modal.classList.remove('open');modal.querySelectorAll('[data-replay]').forEach(x=>x.onclick=()=>{modal.classList.remove('open');location.hash='#/replay/'+encodeURIComponent(x.dataset.replay)})}
function setQuestionCount(n){FabioV2.store.updateSettings({questionCount:n});location.hash='#/practice/'+state.nodeId}
async function randomReplay(){const pool=await FabioV2.store.loadNodeCases(state.nodeId,{limit:2500});if(!pool.length)return;window.FabioV3?.drill?.setFocusNode?.(state.nodeId);window.FabioV3?.drill?.setFilter?.('all');const c=pool[Math.floor(Math.random()*pool.length)];location.hash='#/replay/'+encodeURIComponent(c.id)}
function enhance(){const r=route();if(r.page!=='nodes'||!r.id)return;const gallery=document.querySelector('.gallery');if(!gallery||document.querySelector('#patternLab'))return;state.nodeId=r.id;state.filter='all';state.limit=24;state.shuffle=false;state.selected=[];const section=gallery.closest('.section')||gallery.parentElement;gallery.style.display='none';const lab=document.createElement('div');lab.id='patternLab';lab.innerHTML=`<div class="pl-toolbar"><div class="pl-group"><b>Pattern Wall</b><button data-filter="all" class="active">ALL</button><button data-filter="yes">YES</button><button data-filter="no">NO</button></div><div class="pl-group"><span>圖牆</span><button data-limit="24" class="active">24</button><button data-limit="48">48</button><button data-limit="96">96</button><button id="plShuffle">Shuffle</button></div><div class="pl-group"><span>一鍵開練</span><button data-drill="20">20題</button><button data-drill="50">50題</button><button data-drill="100" class="primary">100題</button></div><span id="patternLabCount"></span><div class="pl-v32-actions" data-node-id="${esc(state.nodeId)}"><button type="button" class="yn" data-v32-yn>YES vs NO 視覺對照</button><button type="button" data-v32-random>隨機開一筆 Replay</button></div></div><div id="patternLabGrid" class="pl-grid"></div><p class="pl-help">點圖＝精準定位 Replay；⇄＝選兩張並排比較。建議先大量看 YES，再大量看 NO，最後混合判斷。</p>`;section.appendChild(lab);lab.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;lab.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});lab.querySelectorAll('[data-limit]').forEach(b=>b.onclick=()=>{state.limit=+b.dataset.limit;lab.querySelectorAll('[data-limit]').forEach(x=>x.classList.toggle('active',x===b));render()});lab.querySelector('#plShuffle').onclick=()=>{state.shuffle=true;render()};lab.querySelectorAll('[data-drill]').forEach(b=>b.onclick=()=>setQuestionCount(+b.dataset.drill));lab.querySelector('[data-v32-yn]').onclick=()=>window.FabioV3?.drill?.compareYesNo?.(state.nodeId);lab.querySelector('[data-v32-random]').onclick=randomReplay;render();document.dispatchEvent(new CustomEvent('fabio:v32-pattern-actions-mounted',{detail:{nodeId:state.nodeId,owner:'pattern-lab'}}))}
const style=document.createElement('style');style.textContent=`
.pl-toolbar{display:flex;flex-wrap:wrap;align-items:center;gap:10px;margin:14px 0;padding:12px;border:1px solid #25354b;border-radius:12px;background:#0d1724}.pl-group{display:flex;gap:6px;align-items:center}.pl-group button{padding:6px 10px}.pl-group button.active{border-color:#55aaff;color:#75baff;background:#11263d}.pl-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.pl-tile{position:relative;border:1px solid #223348;border-radius:10px;background:#0c1521;overflow:hidden}.pl-tile.selected{outline:2px solid #a987ff}.pl-open{display:block;width:100%;text-align:left;border:0;background:transparent;padding:8px;color:inherit}.pl-chart{height:64px}.pl-chart svg{width:100%;height:64px}.pl-u{stroke:#28d5a4;fill:#28d5a4}.pl-d{stroke:#ff6479;fill:#ff6479}.pl-meta{display:flex;justify-content:space-between;gap:6px}.pl-meta span.yes{color:#35dda8}.pl-meta span.no{color:#ff6d7f}.pl-open small{display:block;color:#72839a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pl-compare{position:absolute;right:7px;top:7px;width:28px;height:28px;padding:0;border-radius:50%;background:#101e2e}.pl-compare.on{background:#6d54ba;color:white}.pl-help{color:#8393a8;font-size:12px}.pl-modal{position:fixed;inset:0;background:#0009;z-index:9999;display:none;align-items:center;justify-content:center;padding:24px}.pl-modal.open{display:flex}.pl-modal-card{width:min(1200px,96vw);background:#09131f;border:1px solid #33455f;border-radius:16px;padding:16px}.pl-modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.pl-modal-head div{display:flex;gap:10px;align-items:baseline}.pl-compare-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.pl-compare-pane{border:1px solid #223348;border-radius:12px;padding:12px}.pl-big-chart svg{width:100%;height:220px}.pl-no-preview{display:flex;height:55px;align-items:center;justify-content:center;color:#66788e}@media(max-width:1050px){.pl-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.pl-compare-grid{grid-template-columns:1fr}}`;
document.head.appendChild(style);
new MutationObserver(()=>requestAnimationFrame(enhance)).observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('hashchange',()=>setTimeout(enhance,20));setTimeout(enhance,700);
FabioV2.patternLab={enhance,render,randomReplay};
})();
