window.FabioV2=window.FabioV2||{};
window.FabioV2.nodes=[
{id:'CTX_VALUE',code:'CTX-01',branch:'COMMON',stage:'Context',title:'Previous Value',short:'前日價值區',question:'前一交易日的 VAH / VAL / POC 是否完整可用？',definition:'用前一交易日成交量建立今天的拍賣參考地圖。',yes:'可以進入 Auction 觀察。',no:'NO TRADE：參考地圖不完整。',rule:'previous profile exists && valueWidth > 0',difficulty:1},
{id:'AUC_ATTEMPT',code:'AUC-01',branch:'COMMON',stage:'Auction',title:'Auction Attempt',short:'真正離開 Value',question:'價格是否真正離開 Previous Value，而不是只在 VAH / VAL 邊界抖動？',definition:'市場離開舊 Value 去測試新價格的一次完整拍賣嘗試。',yes:'開始追蹤 Extreme 與外部接受/拒絕。',no:'WAIT：仍是 Value 內旋轉或邊界雜訊。',rule:'excursion >= max(minPoints, valueWidth * excursionPct)',difficulty:1},
{id:'AUC_EXTREME',code:'AUC-02',branch:'COMMON',stage:'Auction',title:'Extreme Expanding',short:'極值擴張',question:'Auction 的 Extreme 是否仍在持續向外擴張？',definition:'同一次 Auction Attempt 中，價格最遠到達的位置。Extreme 在拍賣尚未結束前可以持續更新。',yes:'繼續等待 Rejection 或 Acceptance。',no:'進入結構確認階段。',rule:'new price extends current auction extreme',difficulty:2},
{id:'MR_REJECTION',code:'MR-01',branch:'MR',stage:'Rejection',title:'Rejection',short:'新價格被拒絕',question:'新價格是否被快速拒絕並重新回到舊 Value？',definition:'市場測試外部價格後不願停留，價格重新返回原 Value。',yes:'進入 Mean Reversion「回家」分支。',no:'不要強迫選 MR；繼續檢查 Acceptance。',rule:'clear reclaim before acceptance timeout',difficulty:2},
{id:'MR_CLEAR_RECLAIM',code:'MR-02',branch:'MR',stage:'Reclaim',title:'Clear Reclaim',short:'明確收復',question:'Reclaim 是否夠深、夠快，而不是只碰回 Value 邊界？',definition:'價格不只重新進門，而是深入舊 Value 到預先定義的距離，且在限制時間內完成。',yes:'Failed Auction 確認。',no:'WAIT / INVALID：拒絕證據不足。',rule:'reclaimDepth >= valueWidth * reclaimPct && seconds <= reclaimMaxSec',difficulty:2},
{id:'MR_RECLAIM_LEG',code:'MR-03',branch:'MR',stage:'Causal Leg',title:'Causal Reclaim Leg',short:'因果收復腿',question:'是否已形成當下可確認的 Reclaim Leg？',definition:'Failed Auction 後朝舊 Value 發展的價格腿；必須先出現足夠反向轉折才能確認，禁止事後回看。',yes:'現在才可以對這段 Leg 建 Volume Profile。',no:'WAIT：腿仍在形成。',rule:'turn confirmation >= configured points or valueWidth fraction',difficulty:3},
{id:'MR_LVN',code:'MR-04',branch:'MR',stage:'Location',title:'Reclaim-Leg LVN',short:'收復腿低量谷',question:'Reclaim Leg 上是否存在位置合理、深度合格的 Valley LVN？',definition:'只對 Causal Reclaim Leg 計算 Volume Profile，找兩側較厚、中間明顯偏薄的成交量谷底。',yes:'建立等待 Pullback 的 Location。',no:'NO TRADE：沒有足夠好的位置。',rule:'valleyDepth >= lvnDepth && valuePosition within allowed band',difficulty:4},
{id:'MR_PULLBACK',code:'MR-05',branch:'MR',stage:'Pullback',title:'First Valid Pullback',short:'第一次合法回測',question:'價格是否第一次回到已確認的 LVN，而且沒有追價？',definition:'Leg 與 LVN 已知之後，價格第一次回測該 Location。',yes:'進入 Entry Quality。',no:'WAIT；若錯過第一測則標記 late/second test。',rule:'first touch after lvnReady within tolerance and maxDelay',difficulty:3},
{id:'MR_ENTRY',code:'MR-06',branch:'MR',stage:'Entry',title:'MR Entry Quality',short:'均值回歸進場品質',question:'目前的 Entry、Stop、Target 與時間成本是否仍合理？',definition:'好 Setup 不代表任何價格都能做；確認仍靠近原 Location 且風險報酬沒有被追價破壞。',yes:'EXECUTE MR。',no:'NO TRADE：位置已失真。',rule:'entry distance, structural stop and reward room within strategy config',difficulty:4},
{id:'BO_ACCEPTANCE',code:'BO-01',branch:'BO',stage:'Acceptance',title:'Acceptance',short:'新價格被接受',question:'價格是否持續留在舊 Value 外，形成新的價格接受？',definition:'突破後沒有快速 Clear Reclaim，且時間、成交與位移逐步在 Value 外建立。',yes:'進入 Breakout Retest「搬家」分支。',no:'WAIT：市場仍未給答案。',rule:'outsideRatio >= threshold && displacement >= threshold && no clear reclaim',difficulty:4},
{id:'BO_DISPLACEMENT',code:'BO-02',branch:'BO',stage:'Impulse',title:'Displacement',short:'有效位移',question:'突破是否有足夠連續、快速的單方向 Displacement？',definition:'真正的重新定價，而不是只超過 VAH / VAL 幾點。',yes:'追蹤 Impulse Leg。',no:'NO TRADE：弱突破不追。',rule:'impulse displacement >= configured points/fraction',difficulty:3},
{id:'BO_IMPULSE_LEG',code:'BO-03',branch:'BO',stage:'Causal Leg',title:'Causal Impulse Leg',short:'因果推進腿',question:'Impulse Leg 是否已完成到可以在當下建立 Profile？',definition:'Accepted Breakout 後沿突破方向形成的因果價格腿，需等待轉折確認。',yes:'建立 Impulse-Leg Volume Profile。',no:'WAIT。',rule:'turn confirmation after accepted displacement',difficulty:4},
{id:'BO_LVN',code:'BO-04',branch:'BO',stage:'Location',title:'Impulse-Leg LVN',short:'推進腿低量谷',question:'Impulse Leg 上是否存在合法 LVN？',definition:'Accepted Breakout 的推進腿中，市場快速通過且成交偏薄的位置。',yes:'等待第一次 Pullback。',no:'NO TRADE。',rule:'valleyDepth/location filters pass',difficulty:4},
{id:'BO_PULLBACK',code:'BO-05',branch:'BO',stage:'Pullback',title:'BO First Pullback',short:'突破第一次回測',question:'價格是否第一次 Pullback 到 Impulse-Leg LVN？',definition:'避免突破追價，等價格回到推進腿上的結構位置。',yes:'觀察 Response。',no:'WAIT / 不追價。',rule:'first valid touch after impulse lvn ready',difficulty:3},
{id:'BO_RESPONSE',code:'BO-06',branch:'BO',stage:'Response',title:'Response Confirmation',short:'回測反應',question:'Pullback 後是否停止逆向發展並重新朝突破方向推進？',definition:'突破策略比 MR 更重視新價格持續被接受，因此要求 Location 上出現價格反應。',yes:'進入 Entry Quality。',no:'WAIT / INVALID。',rule:'adverse progress stops and directional progress >= response threshold',difficulty:5},
{id:'BO_ENTRY',code:'BO-07',branch:'BO',stage:'Entry',title:'BO Entry Quality',short:'突破回測進場品質',question:'Acceptance、Stop 與前方 Expansion 空間是否仍有效？',definition:'確認結構失效點明確，且不是在延伸末端追價。',yes:'EXECUTE BO。',no:'NO TRADE。',rule:'acceptance valid && structural stop && reward room pass',difficulty:5},
{id:'WAIT_AMBIGUOUS',code:'WAIT-01',branch:'WAIT',stage:'No Trade',title:'Ambiguous / WAIT',short:'模糊就等待',question:'Rejection 與 Acceptance 是否都還沒有被確認？',definition:'WAIT 是正式市場狀態，不是失敗答案。模糊狀態不強迫分到 MR 或 BO。',yes:'WAIT。',no:'回到已確認的分支。',rule:'neither rejection nor acceptance confirmed',difficulty:3},
{id:'NO_TRADE',code:'NT-01',branch:'WAIT',stage:'No Trade',title:'No Trade',short:'一票否決',question:'是否存在結構不完整、位置失真、第二次測試或風險報酬不合理？',definition:'成熟系統最大的價值之一，是快速排除不值得下注的畫面。',yes:'NO TRADE。',no:'可繼續下一個決策節點。',rule:'invalid structure/location/execution flag',difficulty:2}
];
window.FabioV2.nodeMap=Object.fromEntries(window.FabioV2.nodes.map(n=>[n.id,n]));
window.FabioV2.tree={
MR:['CTX_VALUE','AUC_ATTEMPT','MR_REJECTION','MR_CLEAR_RECLAIM','MR_RECLAIM_LEG','MR_LVN','MR_PULLBACK','MR_ENTRY'],
BO:['CTX_VALUE','AUC_ATTEMPT','MR_REJECTION','BO_ACCEPTANCE','BO_DISPLACEMENT','BO_IMPULSE_LEG','BO_LVN','BO_PULLBACK','BO_RESPONSE','BO_ENTRY']
};
