window.FabioV2=window.FabioV2||{};
window.FabioV2.nodes=[
{id:'CTX_VALUE',code:'CTX-01',branch:'COMMON',stage:'Context',title:'Previous Value',short:'前日價值區',question:'前一交易日的 VAH / VAL / POC 是否完整可用？',definition:'用前一交易日成交量建立今天的拍賣參考地圖。',yes:'可以進入 Auction 觀察。',no:'NO TRADE：參考地圖不完整。',rule:'previous trading-day profile exists && valueWidth > 0',difficulty:1},
{id:'AUC_ATTEMPT',code:'AUC-01',branch:'COMMON',stage:'Auction',title:'Auction Attempt',short:'真正離開 Value',question:'價格是否真正離開 Previous Value，而不是只在 VAH / VAL 邊界抖動？',definition:'市場離開舊 Value 去測試新價格的一次完整拍賣嘗試。',yes:'開始追蹤 Extreme 與外部接受/拒絕。',no:'WAIT：仍是 Value 內旋轉或邊界雜訊。',rule:'excursion >= max(minExcursionPoints, valueWidth * excursionPct)',difficulty:1},
{id:'AUC_EXTREME',code:'AUC-02',branch:'COMMON',stage:'Auction',title:'Extreme',short:'拍賣極值',question:'這次 Auction 的最遠價格在哪裡，並且何時可以因果確認它？',definition:'Anchor 是拍賣最遠價；Decision Time 是拍賣被回收或觀察窗結束、Extreme 才能被鎖定的時間。',yes:'Extreme 已可作為後續結構參考。',no:'拍賣仍在向外擴張。',rule:'anchor = farthest price during auction; decision = auction resolution/timeout, not hindsight anchor time',difficulty:2},
{id:'MR_REJECTION',code:'MR-01',branch:'MR',stage:'Rejection',title:'Rejection',short:'重新進入舊 Value',question:'Extreme 之後是否在限制時間內第一次重新進入舊 Value？',definition:'Rejection 只回答「有沒有重新進門」，不要求已經深入 Value；深入程度由下一個 Clear Reclaim 獨立判斷。',yes:'有初步拒絕證據，繼續檢查 Clear Reclaim。',no:'嚴格 MR Rejection 不成立；但研究母體仍可追蹤晚到的 downstream opportunity。',rule:'first value re-entry after extreme occurs within mrReentryMaxSec',difficulty:2},
{id:'MR_CLEAR_RECLAIM',code:'MR-02',branch:'MR',stage:'Reclaim',title:'Clear Reclaim',short:'明確深入收復',question:'重新進入後，是否在 reclaimMaxSec 內深入舊 Value 至要求深度？',definition:'這是與 Rejection 分離的第二道 Gate：只碰回 VAH/VAL 不算 Clear Reclaim。',yes:'Failed Auction 的收復深度成立。',no:'Rejection 可能存在，但深入程度/速度不足。',rule:'reclaimDepth >= max(3pt, valueWidth*reclaimPct) && elapsedFromExtreme <= reclaimMaxSec',difficulty:2},
{id:'MR_RECLAIM_LEG',code:'MR-03',branch:'MR',stage:'Causal Leg',title:'Causal Reclaim Leg',short:'因果收復腿',question:'Re-entry 後是否形成足夠延伸，並出現 turn confirmation 讓這段 Leg 可在當下封閉？',definition:'Leg 的 Anchor 可以更早，但 Decision 必須等反向轉折確認，避免事後挑腿。',yes:'現在才可以對這段 Leg 建 Volume Profile。',no:'嚴格 Leg 尚未被確認。',rule:'directional reclaim leg followed by opposite turn >= turnPoints within leg window',difficulty:3},
{id:'MR_LVN',code:'MR-04',branch:'MR',stage:'Location',title:'Reclaim-Leg LVN',short:'收復腿低量谷',question:'已確認的 Reclaim Leg 內是否有位置合理、深度達標的 Valley LVN？',definition:'嚴格 LVN 使用 causal reclaim-leg profile；研究母體可保留較淺 candidate 以檢驗 55% Gate 是否真的必要。',yes:'建立嚴格 Pullback Location。',no:'嚴格 LVN Gate 不通過。',rule:'valley exists in reclaim-leg profile && depth >= lvnDepth && location allowed',difficulty:4},
{id:'MR_PULLBACK',code:'MR-05',branch:'MR',stage:'Pullback',title:'First Valid Pullback',short:'第一次合法回測',question:'LVN 已知後，第一次回測是否在嚴格時間窗內抵達 Location？',definition:'Audit Universe 允許較晚 Pullback；嚴格策略只接受 configured max delay 內的第一測。',yes:'進入 Entry Quality。',no:'可能是 late pullback / timeout。',rule:'first touch of strict LVN after LVN-ready within tolerance && pullbackMaxSec',difficulty:3},
{id:'MR_ENTRY',code:'MR-06',branch:'MR',stage:'Entry',title:'MR Entry Quality',short:'均值回歸執行品質',question:'在 terminal pullback 上，結構停損距離與回到 POC 的可用空間是否合理？',definition:'Location 出現不代表任何價格都值得做；Entry Gate 專門檢查風險與空間。',yes:'若所有上游嚴格 Gate 也通過，才 EXECUTE MR。',no:'保留為研究 Opportunity，但嚴格策略不進場。',rule:'riskPoints <= mrEntryMaxRisk && roomToPOC >= mrEntryMinRoomR * riskPoints',difficulty:4},
{id:'BO_DISPLACEMENT',code:'BO-01',branch:'BO',stage:'Displacement',title:'Displacement',short:'有效重新定價',question:'Qualified Auction 是否進一步產生足夠幅度的單方向 Displacement？',definition:'只衡量位移幅度，不把「能不能待在 Value 外」混進同一個 Rule。',yes:'位移 Gate 通過；Acceptance 仍需獨立判斷。',no:'弱位移；但 Audit Universe 仍追蹤其後是否有終端機會。',rule:'excursion >= valueWidth * acceptanceDisplacementPct',difficulty:3},
{id:'BO_ACCEPTANCE',code:'BO-02',branch:'BO',stage:'Acceptance',title:'Acceptance',short:'新價格被接受',question:'Qualified Auction 後的固定觀察窗中，價格是否大部分留在舊 Value 外且沒有重新進入？',definition:'Acceptance 專門衡量「待得住」，不再把 Displacement 門檻重複包進來。',yes:'新價格接受成立。',no:'Value 外停留不足或觀察窗內重新進入。',rule:'outsideRatio >= acceptanceOutsideRatio during acceptanceWindow && no value re-entry in that window',difficulty:4},
{id:'BO_IMPULSE_LEG',code:'BO-03',branch:'BO',stage:'Causal Leg',title:'Causal Impulse Leg',short:'因果推進腿',question:'從 Qualified Auction 起算的順向 Impulse 是否已被 turn confirmation 因果封閉？',definition:'為避免 Displacement Gate 定義自己的母體，Impulse 結構從 qualified auction 起追蹤；嚴格執行仍要求完整 Gate Chain。',yes:'可以建立 Impulse-Leg Volume Profile。',no:'推進腿仍未完成或沒有足夠結構。',rule:'qualified-auction impulse followed by opposite turn >= turnPoints',difficulty:4},
{id:'BO_LVN',code:'BO-04',branch:'BO',stage:'Location',title:'Impulse-Leg LVN',short:'推進腿低量谷',question:'Impulse Leg 自己的價格範圍內是否存在深度合格的 Valley LVN？',definition:'BO LVN 來自 impulse-leg profile，不限制必須落回 Previous Value。Audit 可保留較淺 valley 研究 Gate。',yes:'等待第一次 Pullback。',no:'嚴格 LVN Gate 不通過。',rule:'valley exists in impulse-leg own price range && depth >= lvnDepth',difficulty:4},
{id:'BO_PULLBACK',code:'BO-05',branch:'BO',stage:'Pullback',title:'BO First Pullback',short:'突破第一次回測',question:'Impulse LVN 已知後，第一次 Pullback 是否在嚴格時間窗內抵達？',definition:'研究母體允許較晚 touch，嚴格 BO 只接受 configured max delay 內第一測。',yes:'接著獨立檢查 Response。',no:'late pullback / timeout。',rule:'first touch of impulse-LVN within tolerance && pullbackMaxSec',difficulty:3},
{id:'BO_RESPONSE',code:'BO-06',branch:'BO',stage:'Response',title:'Response Confirmation',short:'回測後重新推進',question:'Pullback touch 後 30 秒內是否重新朝突破方向推進至少 responsePoints？',definition:'Terminal Opportunity 母體在 Pullback 就建立，因此 Response=NO 的案例也會留下，才能實測這個 Gate 是否真的排除壞交易。',yes:'Response Gate 通過。',no:'沒有足夠方向反應；不代表該案例從研究資料消失。',rule:'directional progress from pullback touch >= boResponsePoints within responseMaxSec',difficulty:5},
{id:'BO_ENTRY',code:'BO-07',branch:'BO',stage:'Entry',title:'BO Entry Quality',short:'突破回測執行品質',question:'確認 Response 後的實際執行價，距 structural stop、舊 Value 與 extension 末端是否仍合理？',definition:'Response 與 Entry Quality 是兩個不同 Gate；完整嚴格鏈全部通過才建立真正 BO Entry。',yes:'EXECUTE BO（前提：完整上游 Gate 皆通過）。',no:'保留為研究 Opportunity，但嚴格策略不進場。',rule:'after response: riskPoints <= boEntryMaxRisk && extensionVW <= maxExtension && price remains outside old Value',difficulty:5},
{id:'WAIT_AMBIGUOUS',code:'WAIT-01',branch:'WAIT',stage:'No Trade',title:'Ambiguous / WAIT',short:'模糊就等待',question:'在決策期限內，是否仍沒有足夠證據確認嚴格 Rejection 或 Acceptance？',definition:'WAIT 是正式市場狀態，不強迫把模糊市場塞進 MR 或 BO。',yes:'WAIT。',no:'至少一條嚴格分支已有明確答案。',rule:'strict rejection=false && strict acceptance=false at branch resolution',difficulty:3},
{id:'NO_TRADE',code:'NT-01',branch:'WAIT',stage:'No Trade',title:'No Trade',short:'完整鏈未通過',question:'完整嚴格 Gate Chain 是否有任一必要條件不成立？',definition:'研究 Opportunity 可以存在，但只有完整嚴格鏈通過才是策略 Entry；其他都屬 NO TRADE。',yes:'NO TRADE。',no:'完整策略鏈通過。',rule:'NOT(all required strict strategy nodes == true)',difficulty:2}
];
window.FabioV2.nodeMap=Object.fromEntries(window.FabioV2.nodes.map(n=>[n.id,n]));
window.FabioV2.tree={
MR:['CTX_VALUE','AUC_ATTEMPT','MR_REJECTION','MR_CLEAR_RECLAIM','MR_RECLAIM_LEG','MR_LVN','MR_PULLBACK','MR_ENTRY'],
BO:['CTX_VALUE','AUC_ATTEMPT','BO_DISPLACEMENT','BO_ACCEPTANCE','BO_IMPULSE_LEG','BO_LVN','BO_PULLBACK','BO_RESPONSE','BO_ENTRY']
};
