window.FabioV2=window.FabioV2||{};
(()=>{
const store=FabioV2.store;
if(!store||store.__scanMonitorWrapped)return;
store.__scanMonitorWrapped=true;
const originalApi=store.api;
let currentJob=null,timer=null,lastPercent=0,refreshing=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString();
function duration(sec){sec=Number(sec);if(!Number.isFinite(sec)||sec<0)return'—';if(sec<60)return`${Math.round(sec)}s`;const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=Math.round(sec%60);return h?`${h}h ${m}m`:`${m}m ${s}s`}
function statusLabel(s){return({queued:'QUEUED',running:'RUNNING',done:'DONE',failed:'FAILED'})[s]||String(s||'—').toUpperCase()}
function ensurePanel(){const result=document.querySelector('#scanResult');if(!result)return null;let panel=document.querySelector('#scanMonitor');if(!panel){panel=document.createElement('div');panel.id='scanMonitor';panel.className='scan-monitor';result.insertAdjacentElement('afterend',panel)}const mode=document.querySelector('#contractMode');if(mode&&mode.dataset.causalDefault!=='1'){mode.value='strict';mode.dataset.causalDefault='1';if(!document.querySelector('#contractModeHint')){const hint=document.createElement('small');hint.id='contractModeHint';hint.className='contract-hint';hint.textContent='建議使用 Strict：因果近月規則。Dominant Volume 會使用完整日成交量，只適合研究診斷。';mode.closest('label')?.appendChild(hint)}}return panel}
function render(job){if(!job)return;currentJob=job;const panel=ensurePanel();if(!panel)return;const rawPct=Math.max(0,Math.min(1,Number(job.percent||0)));lastPercent=job.status==='done'?1:Math.max(lastPercent,rawPct);const pct=Math.round(lastPercent*1000)/10;const days=job.days_total?`${num(job.days_processed)} / ${num(job.days_total)}`:(job.trading_days_found?num(job.trading_days_found):'—');const file=job.file?`${esc(job.file)}${job.files_total?` · ${job.file_index||1}/${job.files_total}`:''}`:'準備中';const rows=job.work_rows_total?`${num(job.work_rows_processed)} / ${num(job.work_rows_total)}`:'—';const source=job.source_rows_total?num(job.source_rows_total):'—';const logs=(job.logs||[]).slice(-10).reverse();const nodes=Object.entries(job.node_counts||{}).sort((a,b)=>(b[1].total||0)-(a[1].total||0)).slice(0,12);panel.innerHTML=`
<div class="scan-head"><div><span class="scan-state ${esc(job.status)}">${statusLabel(job.status)}</span><b>Job ${esc(job.job_id)}</b><small>${esc(job.phase_label||job.phase||'等待進度')}</small></div><strong>${pct.toFixed(1)}%</strong></div>
<div class="scan-bar"><i style="width:${pct}%"></i></div>
<div class="scan-current"><div><span>目前檔案</span><b>${file}</b></div><div><span>目前日期 / 合約</span><b>${esc(job.current_day||'—')} ${esc(job.current_contract||'')}</b></div><div><span>階段</span><b>${esc(job.phase||'—')}</b></div><div><span>Heartbeat</span><b>${esc(job.heartbeat_at?new Date(job.heartbeat_at).toLocaleTimeString():'—')}</b></div></div>
<div class="scan-metrics"><div><span>原始 Rows</span><b>${source}</b></div><div><span>3-pass 工作量</span><b>${rows}</b></div><div><span>交易日</span><b>${days}</b></div><div><span>Events</span><b>${num(job.events)}</b></div><div><span>MR</span><b>${num(job.mr)}</b></div><div><span>BO</span><b>${num(job.bo)}</b></div><div><span>WAIT</span><b>${num(job.wait)}</b></div><div><span>Entries</span><b>${num(job.entries)}</b></div></div>
<div class="scan-speed"><span>已用 ${duration(job.elapsed_seconds)}</span><span>ETA ${duration(job.eta_seconds)}</span><span>${job.work_rows_per_sec?`${num(job.work_rows_per_sec)} work rows/s`:'速度計算中'}</span></div>
${job.message?`<div class="scan-message ${job.status==='failed'?'error':''}">${esc(job.message)}</div>`:''}
${nodes.length?`<details class="scan-nodes" open><summary>即時 Decision Node 數量</summary><div class="scan-node-grid">${nodes.map(([id,x])=>`<div><b>${esc(id)}</b><span>${num(x.total)} cases</span><small>YES ${num(x.yes)} · NO ${num(x.no)}</small></div>`).join('')}</div></details>`:''}
<details class="scan-log" ${job.status==='failed'?'open':''}><summary>最近 Scanner 訊息 (${(job.logs||[]).length})</summary>${logs.length?logs.map(x=>`<div><time>${esc(x.at?new Date(x.at).toLocaleTimeString():'')}</time><b>${esc(x.phase||'')}</b><span>${esc(x.message)}</span></div>`).join(''):'<p>等待第一個 heartbeat…</p>'}</details>`;
const btn=document.querySelector('#scanBtn');if(btn){const busy=job.status==='queued'||job.status==='running';btn.disabled=busy;btn.textContent=busy?`掃描中 ${pct.toFixed(1)}%`:'開始掃描 Event Store'}const result=document.querySelector('#scanResult');if(result)result.textContent=job.status==='running'?`Job ${job.job_id} 正在執行：${job.phase_label||job.phase}`:job.status==='done'?`Job ${job.job_id} 完成：${num(job.events)} events`:job.status==='failed'?`Job ${job.job_id} 失敗：${job.message||''}`:`Job ${job.job_id}：${job.status}`}
async function poll(){if(!currentJob?.job_id)return;try{const j=await originalApi('/scan/'+encodeURIComponent(currentJob.job_id));render(j);if(j.status==='done'||j.status==='failed'){stop();if(j.status==='done'&&!refreshing){refreshing=true;try{await store.boot();FabioV2.app?.render?.()}finally{refreshing=false;setTimeout(()=>render(j),0)}}}}catch(e){const panel=ensurePanel();if(panel)panel.insertAdjacentHTML('beforeend',`<div class="scan-message error">進度查詢失敗：${esc(e.message)}</div>`)} }
function stop(){if(timer){clearInterval(timer);timer=null}}
function start(job){stop();lastPercent=0;currentJob=job;render(job);if(job.status==='queued'||job.status==='running'){timer=setInterval(poll,1000);poll()}}
store.api=async function(path,opts){try{const r=await originalApi(path,opts);if(path==='/scan'&&(opts?.method||'GET').toUpperCase()==='POST'&&r?.job_id)start(r);return r}catch(e){if(path==='/scan'&&String(e.message).startsWith('409')){try{const s=await originalApi('/scan/status');const active=(s.items||[]).slice().reverse().find(x=>x.status==='running'||x.status==='queued');if(active){start(active);return active}}catch{} }throw e}};
async function attach(){const panel=ensurePanel();if(!panel||currentJob)return;try{const s=await originalApi('/scan/status');const items=s.items||[];const active=items.slice().reverse().find(x=>x.status==='running'||x.status==='queued');const latest=active||items[items.length-1];if(latest)start(latest)}catch{} }
const observer=new MutationObserver(()=>{if(document.querySelector('#scanResult'))attach();else if(location.hash&&!location.hash.includes('/data'))stop()});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(attach,0));setTimeout(attach,0);
FabioV2.scanMonitor={start,poll,get current(){return currentJob}};
})();
