// Offline screenshot fallback only. Production/GitHub CI loads official KLineChart 10.0.2 first.
if(!window.klinecharts){
  const charts=new Map();
  function makeChart(id){
    const el=typeof id==='string'?document.getElementById(id):id; el.innerHTML='';
    const canvas=document.createElement('canvas');canvas.style.width='100%';canvas.style.height='100%';canvas.width=el.clientWidth||1000;canvas.height=el.clientHeight||600;el.appendChild(canvas);
    const ctx=canvas.getContext('2d');const state={data:[],overlays:[]};
    const draw=()=>{const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#08101c';ctx.fillRect(0,0,W,H);if(!state.data.length)return;const pad={l:18,r:70,t:18,b:92};const cw=W-pad.l-pad.r,ch=H-pad.t-pad.b;let lo=Math.min(...state.data.map(b=>b.low)),hi=Math.max(...state.data.map(b=>b.high));state.overlays.forEach(o=>o.points?.forEach(p=>{if(Number.isFinite(p.value)){lo=Math.min(lo,p.value);hi=Math.max(hi,p.value)}}));const span=Math.max(1,hi-lo);const y=v=>pad.t+(hi-v)/span*ch;ctx.strokeStyle='#14253a';ctx.lineWidth=1;for(let j=0;j<7;j++){const yy=pad.t+j*ch/6;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(W-pad.r,yy);ctx.stroke();ctx.fillStyle='#71839b';ctx.font='11px sans-serif';ctx.fillText((hi-j*span/6).toFixed(0),W-pad.r+8,yy+4)};const step=cw/state.data.length;state.data.forEach((b,i)=>{const x=pad.l+(i+.5)*step;const up=b.close>=b.open;ctx.strokeStyle=up?'#22c89a':'#f05469';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(x,y(b.high));ctx.lineTo(x,y(b.low));ctx.stroke();const top=Math.min(y(b.open),y(b.close)),h=Math.max(1,Math.abs(y(b.open)-y(b.close)));ctx.fillRect(x-Math.max(1,step*.28),top,Math.max(2,step*.56),h)});state.overlays.forEach(o=>{if(!o.points?.length)return;const v=o.points[0].value;if(!Number.isFinite(v))return;const yy=y(v);const color=o.styles?.line?.color||'#9b7cff';ctx.strokeStyle=color;ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(W-pad.r,yy);ctx.stroke();ctx.setLineDash([])});ctx.fillStyle='#72859d';ctx.font='11px sans-serif';const first=new Date(state.data[0].timestamp),last=new Date(state.data.at(-1).timestamp);ctx.fillText(first.toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false}),pad.l,H-58);ctx.fillText(last.toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false}),W-pad.r-42,H-58)};
    const chart={setSymbol(){},setPeriod(){},setDataLoader(loader){loader.getBars({callback:data=>{state.data=data;draw()}})},createIndicator(){},createOverlay(o){state.overlays.push(o);draw();return String(state.overlays.length)},resize(){canvas.width=el.clientWidth;canvas.height=el.clientHeight;draw()}};charts.set(id,chart);return chart
  }
  window.klinecharts={__offlineFallback:true,init:makeChart,dispose(id){const el=document.getElementById(id);if(el)el.innerHTML='';charts.delete(id)}}
}
