const $=s=>document.querySelector(s)
const state={data:null,case:null,bars:[],visible:0,playing:false,timer:null,q:0,revealed:0,score:0,answered:0,answers:[],chart:null,qStartedAt:0,showTrade:false,period:'minute'}
function ensureTraditionalChineseLocale(){if(typeof klinecharts?.registerLocale==='function')klinecharts.registerLocale('zh-TW',{time:'時間：',open:'開：',high:'高：',low:'低：',close:'收：',volume:'量：',change:'漲跌：',turnover:'成交額：',second:'秒',minute:'分鐘',hour:'小時',day:'天',week:'週',month:'月',year:'年'});window.FabioOverlays?.register?.()}
const glossary={AUCTION:'Auction Attempt＝市場離開舊 Value 去測試新價格。先確認真的出去試價，不要把邊界抖動當突破。',REJECTION:'Rejection＝新價格沒有被接受，價格快速回到舊 Value。Clear Reclaim 要求回得夠深、夠快。',ACCEPTANCE:'Acceptance＝突破後持續在 Value 外成交，沒有快速回舊 Value，並開始形成新的價格接受。','CAUSAL LEG':'Causal Leg＝在當下已能確認的價格腿，不可事後看完整段才回頭畫。',LOCATION:'LVN＝該 Causal Leg 上成交量明顯偏薄的價格谷底；它回答在哪裡做。',ENTRY:'First Valid Pullback＝Leg 與 LVN 確立之後，價格第一次回到合法 LVN。錯過不追。',DISPLACEMENT:'Displacement＝突破後明顯、連續、快速的價格位移，代表市場正在重新定價。','IMPULSE LEG':'Impulse Leg＝Accepted Breakout 後沿突破方向形成的因果推進腿；腿未完整時應 WAIT。'}
const questions={MR:[['AUCTION','價格是否真正離開 Previous Value？','不要把 VAH/VAL 附近 1～2 點抖動當成 Auction Attempt。',true,'市場已經離開 Value，形成可追蹤的拍賣嘗試。'],['REJECTION','新價格是否被快速拒絕並 Clear Reclaim？','被拒絕才進入「回家」的均值回歸路徑。',true,'這是一個 Failed Auction：外部價格沒有被接受。'],['CAUSAL LEG','是否已形成可確認的 Reclaim Leg？','不能事後畫腿；當下必須已有足夠位移與轉折確認。',true,'Reclaim Leg 已成立，現在才有資格對這段畫 Volume Profile。'],['LOCATION','Reclaim Leg 上是否存在合法 LVN？','LVN 是位置，不是單獨的進場訊號。',true,'找到低成交谷底，可等待第一次合法 Pullback。'],['ENTRY','現在是否已到第一個合法 LVN Pullback？','錯過就不要追；好 Setup 不代表任何價格都值得進。',true,'符合 Entry 條件，可以進入 Execution。']],BO:[['AUCTION','價格是否真正離開 Previous Value？','先確認是 Auction Attempt，不猜突破真假。',true,'市場已經離開舊 Value。'],['REJECTION','市場是否已經快速 Clear Reclaim 回舊 Value？','如果 YES 應轉去評估 Mean Reversion。',false,'沒有快速 Reclaim，仍需繼續觀察 Acceptance。'],['ACCEPTANCE','價格是否持續留在 Value 外並形成 Acceptance？','看停留、位移與外部成交，不用一根 K 棒定生死。',true,'新價格正在被接受，進入突破回測候選。'],['DISPLACEMENT','是否有足夠的單方向 Displacement？','弱突破不追；要看到真正重新定價。',true,'Displacement 成立。'],['IMPULSE LEG','Impulse Leg 是否已完整到可以畫 Profile？','尚未形成完整腿就應 WAIT。',false,'目前答案是 WAIT：讓市場先把腿走完整。']]}
function decodeSecondBars(){const s=window.__SECOND_BARS__;if(!s?.rows)return null;const k=['timestamp','open','high','low','close','volume','firstSeq','lastSeq'];return s.rows.map(r=>Object.fromEntries(k.map((x,i)=>[x,r[i]])))}
function decisionTimeFor(i){const c=state.case;if(c.strategy==='MR')return[c.attemptStartTime,c.clearReclaimTime,c.turnConfirmTime,c.turnConfirmTime,c.entryTime][i]||c.extremeTime;return[c.attemptStartTime,c.extremeTime,c.extremeTime,c.extremeTime,c.extremeTime][i]||c.extremeTime}
function toLocalEpoch(bars){const first=bars?.[0];if(!first||typeof first.timestamp!=='number')return bars;const off=new Date(first.timestamp).getTimezoneOffset();if(!off)return bars;return bars.map(x=>({...x,timestamp:x.timestamp+off*60000}))}
function caseBars(c){const sec=decodeSecondBars();if(sec&&window.__SECOND_BARS__.date===c.date){const a=Date.parse(c.attemptStartTime)-180000,b=Date.parse(c.attemptStartTime)+720000;state.period='second';return toLocalEpoch(sec).filter(x=>x.timestamp>=a&&x.timestamp<=b)}state.period='minute';return toLocalEpoch(state.data.sessions[c.date].bars)}
async function boot(){ensureTraditionalChineseLocale();state.data=window.__REPLAY_DATA__||await(await fetch('./public/data/demo_case.json')).json();const sel=$('#caseSelect'),u=state.data.cases.filter(c=>c.strategy==='MR').concat(state.data.cases.filter(c=>c.strategy==='BO').slice(0,20));u.forEach(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=`${c.date} · ${c.strategy==='MR'?'均值回歸':'突破回測'} · ${c.direction==='long'?'多':'空'}`;sel.appendChild(o)});const p=u.find(c=>c.id.includes('2026-08-11-MR-10'))||u[0];sel.value=p.id;sel.onchange=()=>loadCase(sel.value);$('#yesBtn').onclick=()=>answer(true);$('#noBtn').onclick=()=>answer(false);$('#playBtn').onclick=togglePlay;$('#stepBtn').onclick=()=>step(1);$('#backBtn').onclick=()=>step(-1);$('#timeline').oninput=e=>{state.visible=+e.target.value;renderChart()};$('#speedSelect').onchange=()=>{if(state.playing){stopPlay();startPlay()}};$('#glossaryBtn').onclick=()=>$('#glossary').classList.toggle('hidden');await loadCase(p.id)}
async function loadCase(id){state.case=state.data.cases.find(c=>c.id===id);state.bars=caseBars(state.case);Object.assign(state,{q:0,revealed:0,score:0,answered:0,answers:[],showTrade:false});stopPlay();updateMeta();updateQuestion();setVisibleToTime(decisionTimeFor(0));renderDecisionLog();renderChart()}
function setVisibleToTime(time){const t=Date.parse(time||state.case.attemptStartTime);let idx=-1;state.bars.forEach((b,i)=>{if(b.timestamp<=t)idx=i});state.visible=Math.max(10,Math.min(state.bars.length,idx+1));$('#timeline').min=10;$('#timeline').max=state.bars.length;$('#timeline').value=state.visible}
function updateMeta(){const c=state.case,p=c.priorProfile;$('#sessionLabel').textContent=`${c.date} · ${state.period==='second'?'1秒 Replay':'1分 Replay'}`;$('#vahText').textContent=p.vah.toFixed(0);$('#pocText').textContent=p.poc.toFixed(0);$('#valText').textContent=p.val.toFixed(0);$('#eventTime').textContent=timeOnly(c.attemptStartTime);$('#extremeText').textContent='尚未揭曉';$('#lvnText').textContent='尚未揭曉';$('#entryText').textContent='尚未揭曉';$('#scoreText').textContent='0';updateBranch()}
function qlist(){return questions[state.case.strategy]||questions.BO}
function updateQuestion(){const q=qlist()[state.q]||qlist().at(-1);$('#questionTag').textContent=`Q${state.q+1} · ${q[0]}`;$('#questionText').textContent=q[1];$('#questionHint').textContent=q[2];$('#feedback').className='feedback muted';$('#feedback').textContent='選擇答案後才顯示解析。';$('#glossary').textContent=glossary[q[0]]||'此節點用來確認市場結構。';$('#glossary').classList.add('hidden');$('#reactionTime').textContent='判斷計時中';state.qStartedAt=performance.now();document.querySelectorAll('.route-node').forEach((n,i)=>n.classList.toggle('active',i===Math.min(state.q,4)));updateBranch()}
function updateBranch(){document.querySelectorAll('.branch').forEach(x=>x.classList.remove('active'));let key='wait';if(state.case?.strategy==='MR'&&state.revealed>=2)key='mr';if(state.case?.strategy==='BO'&&state.revealed>=3)key='bo';document.querySelector(`.branch.${key}`)?.classList.add('active');$('#strategyBadge').textContent=key==='mr'?'MR · 回家':key==='bo'?'BO · 搬家':'WAIT'}
function answer(v){const q=qlist()[state.q];if(!q)return;const ms=Math.round(performance.now()-state.qStartedAt),ok=v===q[3];state.answered++;if(ok)state.score++;state.revealed=Math.max(state.revealed,state.q+1);state.answers.push({q:state.q+1,tag:q[0],choice:v?'YES':'NO',ok,ms});$('#scoreText').textContent=Math.round(state.score/state.answered*100);$('#reactionTime').textContent=`${(ms/1000).toFixed(1)} 秒`;const f=$('#feedback');f.className=`feedback ${ok?'good':'bad'}`;f.textContent=(ok?'✓ 判斷正確：':'✕ 再想一下：')+q[4];renderDecisionLog();renderChart();setTimeout(()=>{if(state.q<qlist().length-1){state.q++;setVisibleToTime(decisionTimeFor(state.q));updateQuestion();renderChart()}else revealOutcome()},700)}
function renderDecisionLog(){const e=$('#decisionLog');$('#decisionCount').textContent=state.answers.length;if(!state.answers.length){e.textContent='尚未作答';return}e.innerHTML=state.answers.map(a=>`<div class="log-row"><span>Q${a.q} ${a.tag} · ${a.choice}</span><span class="${a.ok?'pass':'fail'}">${a.ok?'✓':'✕'} ${(a.ms/1000).toFixed(1)}s</span></div>`).join('')}
function revealOutcome(){const c=state.case;state.showTrade=true;if(c.entryTime){$('#entryText').textContent=`${c.entryPrice.toFixed(0)} @ ${timeOnly(c.entryTime)}`;$('#strategyBadge').textContent=c.direction==='long'?'EXECUTE LONG':'EXECUTE SHORT';setVisibleToTime(new Date(Date.parse(c.entryTime)+90000).toISOString())}else{$('#entryText').textContent='WAIT / NO TRADE';$('#strategyBadge').textContent=c.strategy==='MR'?'MR · WAIT':'BO · WAIT';setVisibleToTime(new Date(Date.parse(c.extremeTime)+180000).toISOString())}renderChart()}
function step(n){state.visible=Math.max(10,Math.min(state.bars.length,state.visible+n));$('#timeline').value=state.visible;renderChart()}function togglePlay(){state.playing?stopPlay():startPlay()}function startPlay(){state.playing=true;$('#playBtn').textContent='Ⅱ';state.timer=setInterval(()=>state.visible>=state.bars.length?stopPlay():step(1),+$('#speedSelect').value)}function stopPlay(){state.playing=false;$('#playBtn').textContent='▶';if(state.timer)clearInterval(state.timer);state.timer=null}function timeOnly(s){return s?s.slice(11,19):'—'}
function priceAt(time){const t=Date.parse(time);let b=null;for(const x of state.bars){if(x.timestamp<=t)b=x;else break}return b?.close}
function renderChart(){const bars=state.bars.slice(0,state.visible);if(!bars.length)return;const last=bars.at(-1);$('#replayClock').textContent=new Date(last.timestamp).toLocaleString('zh-TW',{hour12:false});$('#barStats').textContent=`O ${last.open.toFixed(0)}  H ${last.high.toFixed(0)}  L ${last.low.toFixed(0)}  C ${last.close.toFixed(0)}`;if(state.chart){try{klinecharts.dispose('chart')}catch(e){}}const chart=klinecharts.init('chart',{locale:'zh-TW',timezone:'Asia/Taipei',layout:{barSpaceLimit:{min:2,max:18}},styles:{grid:{horizontal:{color:'#1b2b40'},vertical:{color:'#152438'}},candle:{bar:{upColor:'#22c89a',downColor:'#f05469',upBorderColor:'#22c89a',downBorderColor:'#f05469',upWickColor:'#22c89a',downWickColor:'#f05469'}}}});state.chart=chart;chart.setSymbol({ticker:'MTX202608',pricePrecision:0,volumePrecision:0});chart.setPeriod({span:1,type:state.period});chart.setDataLoader({getBars:({callback})=>callback(bars,{forward:false,backward:false})});try{chart.createIndicator('VOL',{pane:{height:80}})}catch(e){}setTimeout(()=>drawStructure(chart,bars),80)}
function drawStructure(chart,bars){const c=state.case,p=c.priorProfile,t0=bars[0].timestamp,t1=bars.at(-1).timestamp;const level=(v,color)=>{try{chart.createOverlay({name:'horizontalSegment',lock:true,points:[{timestamp:t0,value:v},{timestamp:t1,value:v}],styles:{line:{color,size:1,style:'dashed'}}})}catch(e){}};level(p.vah,'#ff667d');level(p.poc,'#f2bb57');level(p.val,'#2bd7a5');if(state.revealed>=1)window.FabioOverlays?.marker(chart,{time:c.attemptStartTime,value:priceAt(c.attemptStartTime),label:'Auction',side:c.direction,kind:'event',color:'#52a7ff'});if(state.revealed>=2){$('#extremeText').textContent=`${c.extremePrice?.toFixed?.(0)||c.extremePrice} @ ${timeOnly(c.extremeTime)}`;window.FabioOverlays?.marker(chart,{time:c.extremeTime,value:c.extremePrice,label:'Extreme',side:c.direction,kind:'extreme',color:'#ff9d57'});if(c.clearReclaimTime)window.FabioOverlays?.marker(chart,{time:c.clearReclaimTime,value:c.clearReclaimPrice,label:'Clear Reclaim',side:c.direction,kind:'event',color:'#64d4ff'})}if(state.revealed>=3&&c.turnConfirmTime)window.FabioOverlays?.leg(chart,{time1:c.extremeTime,value1:c.extremePrice,time2:c.turnConfirmTime,value2:priceAt(c.turnConfirmTime),label:c.strategy==='MR'?'Reclaim Leg':'Impulse Leg',color:'#a58bff'});if(state.revealed>=4&&c.lvn){$('#lvnText').textContent=c.lvn.toFixed(0);level(c.lvn,'#9b7cff')}if(state.showTrade&&c.entryTime){window.FabioOverlays?.marker(chart,{time:c.entryTime,value:c.entryPrice,label:`ENTRY ${c.entryPrice.toFixed(0)}`,side:c.direction,kind:'entry'});level(c.stop,'#ff5d74');level(c.target,'#26d7a2')}}
boot().catch(err=>{console.error(err);$('#engineBadge').textContent='啟動失敗';$('#engineBadge').className='badge'})
